### ISSUE TITLE
Feature request: Vehicle message, in case of obstacle, if it is blocked - Fahrzeugmeldung, bei Hindernis,wenn es blockiert ist

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1001]
Feature request:
Is it possible to display a message when a vehicle is blocked/disabled, similar to "Destination reached"?
Sometimes a vehicle cannot continue driving if it is blocked by something (collision detection, getting stuck on an object). You don't notice it because no message is displayed.
Greetings Micha
++++++++++++++++++++++++++++++++++
Feature request:
ist es möglich, bei blockade/behinderung eines Fahrzeuges eine Meldung anzuzeigen, ähnlich wie bei "Ziel erreicht"?
Manchmal kann ein Fahrzeug die Fahrt nicht fortsetzen, wenn es durch irgendetwas blockiert wird (kollission-abfrage, hängen bleiben an einem Gegenstand). Man bekommt es nicht mit, da keine Meldung angezeigt wird.
Gruss Micha

**Comment by BloodyRain2k** [comment]
It's weird because an older version before the in-game editor had this exact feature, even though it had a lot of false positives but it was still better than not noticing that your truck's stuck since half an hour, but then this message was gone.

And yeah, for mentioned reasons I'd also like this to be added again.

Also on a related note: please stop AD from constantly turning off and on again the engine when it encounters a spot where it thinks it can't go. Most of the times when it gets stuck for me due to the Collision Avoidance (yes I know I can turn it off, but then the AI traffic messes them up in another way) it stays in place and keeps turning on and off the engine just for moving 1mm...
