### ISSUE TITLE
AutoDrive doesn't work in version 1.0.7.0, previous version working 1.0.6.6

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#1005]
AutoDrive Version: 1.0.7.0
Release or custom zip: Custom Zip

When downladed latest version from Github, The mod didn't appear to be selected,

I have to be back to version 1.0.6.6 to work correctly.

**Comment by Flashsolutions** [comment]
I believe this is because 1.0.7.0 requires patch level 1.5 on Farm Simulator.  I had the same problem.  That said, you might want to only update to 1.0.6.9 because 1.0.7.0 has introduced so many bugs it is nearly unusable (for me at least).  I have not had time to document them all, but I am just trying to do simple combine unload and sell with a single tractor trailer and gave up and went back to 1.0.6.9 for the time being.

**Comment by PromGames** [comment]
Just installed the new update 1.5 and everything works.

Thanks, Item close
