### ISSUE TITLE
Destinations translations data automatically created

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#1016]
**Is your feature request related to a problem? Please describe.**
The problem are the language in the titles. I use to play German maps from my team I was wondering if would be possible to add the posibility of translations and collecting global company productions based and standard hotspots defined in map.xml

**Describe the solution you'd like**
To have sets of language translations automatically created from the map.xml and the global company productions. It would be nice to have the possibility of creating a table with destinations in the savegame in xml format filled with the sets of translations collected with this data and  when a destination is created and you write in German and is coincident with this table, we will have the possibility of switch the language to be displayed a selection button for language desired from the table the system is creating itself. This table can to be saved in xml in I_10 format standard.

The global company productions destinations is very good source of data. I am playing hopfach from deQx and the AD allows you to really work on very intensive productions factories. it has a complete range of AD routes for global company productions. 

The AD routes where created by der_mali that made and incredible job. Sorry for the 6 mb of routes, it get the system hard to recalculate, but everything in hopfach is get the system at the extreme with 1.5 gb map. However, ram consumption is around 1.2 gb. The usage of pallets storage save a lot of ram usage. 

Regards 

Prom

**Comment by Roby1164** [comment]
In my opinion, it would penalize others, since maps with the integrated GC, and in particular the German ones, give problems with other languages. And I also think that the problem you find is really due to the GC files contained in the maps, which do not get along with the game. I have asked around several times, in the various forums, especially on the LS one, to highlight the problem of translations, but always promptly ignored ....
And if we were to make sure that AD took the data from the GC files, I am almost certain, that we would find ourselves with a confusion, and many descriptions exclusively in German.

**Comment by Dzi4d3k** [comment]
Already denied:
https://github.com/Stephan-S/FS19_AutoDrive/issues/705

**Comment by PromGames** [comment]
Thx, I didn’t see it
