### ISSUE TITLE
Yellow Line for Next waypoint isnt changing waypoint when pushing button.

### ISSUE THREAD

**Issue by MiSpA51** [Stephan-S/FS19_AutoDrive#1021]
Hey Guys,

I loaded in a premade config from Eiersholt.
The problem im having now is that when I want to add a route in I cant change the yellow line.

It stays/sticks at a waypoint (always the same one) on the map. Also when i drive to that waypoint and delete it it will go 1 waypoint back and sticks there. So or this is a bug and that button isnt working or im doing someting wrong...

Some extra info. The waypoint the yellow line sticks to is like 5 minuts driving from where im putting the new route/waypoints in. Version 1.0.7.0

Greets MiSpA51

**Comment by StuartLivings** [comment]
I'm able to consistently reproduce this symptom in multiplayer when editing waypoints on a device other than the multiplayer server.  If editing the waypoints on the server this does not occur.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
