### ISSUE TITLE
MP: can't record routes

### ISSUE THREAD

**Issue by DonHarlem78** [Stephan-S/FS19_AutoDrive#1023]
Woran kann es liegen dass ich im MP, auf dem gemieteten Server keine Routen aufzeichnen / bearbeiten kann. Bekomme zwar die bestehenden Routen angezeigt , kann die Aufnahme auch starten aber es wird weder etwas aufgezeichnet oder bearbeitet.
Im SP läuft alles problemlos

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
