### ISSUE TITLE
Unload Bunker silo mode bug.

### ISSUE THREAD

**Issue by superkefir** [Stephan-S/FS19_AutoDrive#1035]
AutoDrive Version: 1.0.7.0
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable):

Hello Stephan!
Happy New Year!
I tried to check how the Unload Bunker silo mode works. So i get the W190D with showel and push start. The showel goes up and stay there then it starts to fill up the showel. But the loading position wasn't set. On other machine the same situation. I record the video to show how it works now.

https://www.youtube.com/watch?v=55tDGOuVQ9U&feature=youtu.be

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
