### ISSUE TITLE
MP: Some visual animations are not working

### ISSUE THREAD

**Issue by jspring0811** [Stephan-S/FS19_AutoDrive#1041]
AutoDrive Version: 1.0.7.0

On dedi server some visual animations are not working correctly.  For example: "Unload bunker silo" only the bucket moves... the arm of the loader does not move.   I have also seen this same type of issue in dedi Courseplay.   However, functionally, they are working.  If you run the loader manually, the visual animations are working correctly.

![loader-arm](https://user-images.githubusercontent.com/48362683/71993109-8cb2af80-3204-11ea-9888-21488ea3b944.png)

**Comment by Iwan1803** [comment]
Could you try it in SP?

**Comment by jspring0811** [comment]
If SP means Single Player / Career Mode then, yes, they work fine in single player career mode.  I just retested several loaders on both Dedi and single player.

New Holland Wheel Loader, CLAAS Wheel Loader, Manitou Telehandler, and John Deere 6R with Front Loader.

None of the vehicles I tested worked in dedi (loader arms do not visually move but the bucket does).  All of them worked fine in single/career.

Thanks!

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
