### ISSUE TITLE
AD does not fill both products (Solid Fertilizer and Seeds)

### ISSUE THREAD

**Issue by KCHARRO** [Stephan-S/FS19_AutoDrive#1079]
AutoDrive Version: 1.0.7.0-36
Release or custom zip: both 
Map (if applicable): Anyone
Vehicle/type (applicable): Helper with Seeders & Planters

I'm sorry if this has been mentioned in another problem, most are in German ...

When an assistant is with CP, when one of the two seeder tanks remains empty, AD should fill both Fertilizer and Seeds, this worked well in versions 1.0.6, since versions 1.0.7 only fill in one kind of product.

I remember that there was a switch that allowed you to choose whether to load both when one was empty or not in seeders and planters.

At the moment when the assistant is going to fill, if we tell him to load Solid Fertilizer he stops and refills it, but even passing under one of Seeds he does not detect the trigger and does not stop to fill.

For now in solution to this I only use seeders and planters with a single tank.

Could you add this function again? Let me decide whether to recharge both Fertilizer and Seeds when one of the two is selected.

And good work to make AD and Courseplay work together as one.

**Comment by Stephan-S** [comment]
Hey @KCHARRO ,
the setting is now missing since it is always activated. The only limitation is the distance between your two loading points.
You can set this with the "Maximum trigger range" setting in the options. As long as your additional loading point (the one you didn't select as filltype) is not further away from the target loading point then this settings value, they should load at this trigger as well.

But I have to check the code if this also works if you do this in reverse order (so the selected trigger comes before the additional one) but this should work in the radius.

Can you please recheck this and come back here? Thank you

**Comment by Iwan1803** [comment]
Some seed machines must be extended so that the filling hatch can be opened. So they are causing problems.
I'm using the silo from Holger-70, the Horsch pack from the modhub and they are working great:
https://www.modhoster.de/mods/befullbare-lager-kalk-dunger-saatgut
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=127499&title=fs2019
I have placed both silos directly behind each other and specified the 2nd as target and what can be loaded there:
![fsScreen_2020_02_16_11_06_53](https://user-images.githubusercontent.com/47528836/74602961-5fcca480-50ae-11ea-8c16-2d1edd9b2497.jpg)

**Comment by Stephan-S** [comment]
I made some changes in the last version. Could you please use the latest version and try again? Thank you :-)

**Comment by KCHARRO** [comment]
Hi @Stefan

It works, both are filled in, I tried it now in my work. As in the picture above.

Thanks for fixing it.

But don't close this thread, I'll try it tonight in home with all the mods I have to see if it gives any compatibility problem. because I saw something strange with VCA, the first time, it filled the seeds, then when it reached 100% with fertilizer, the VCA gave an error (sometimes it happens when it stops and starts again; something with the gears; """it is the first time it influences AD""") followed AutoDrive gave another and I had to close the game with Alt-F4. Blocked completely, (even the log did not save it).

Then I tried 4-5 times and everything works 100%

Mods Used:

GitHub - AutoDrive: 1.0.7.1 Zip Release
GitHub - Courseplay:  6.0.1.00385
GitHub - VCA:  0.1.0.6
GitHub - TSX EnhancedVehicle: 1.6.3.1
Giants ModHub - REA: 1.1.0.0
Giants ModHub - Placeable Buying Stations 1.0.1.0

Map: Felsbrunn
Tractor: Fendt 500
Seeder: Horsh Pronto 9DC

**Comment by KCHARRO** [comment]
Hi @ Stefan, I'm back, Good news ...

Last night I tested with 118 active mods, differents seeders & planters on several maps. Log free errors, at least for now. 

Good job, I know it's complicated and takes a lot of time.

The error of the VCA was only some chance of those rare, like Windows that sometimes gives a blue screen and then reboots and you never know what happened.

All 100%

You can now close this issue, and one more time Thank You for creating this fantastic Mod
