### ISSUE TITLE
Tractors not driving at full speed

### ISSUE THREAD

**Issue by guitarheel** [Stephan-S/FS19_AutoDrive#1114]
AutoDrive Version: 1.0.7.1
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**
When pulling an implement in drive mode, the tractor does not drive at full speed.

**If applicable - Steps to reproduce the behavior**
Hook to an implement, attempt to autodrive from shop to farm.  Tractor does 8mph instead of 26mph.  This speed varies depending on implements connected.  Implement is not deployed or lowered.  Tractor drives at full speed when AutoDrive is not enabled. 

**Screenshots**

**Comment by Iwan1803** [comment]
Maybe a wrong setting or strange network?
Please post the log and a screenshot.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
