### ISSUE TITLE
AutoDriveTrailerUtil.lua:620: attempt to index a nil value

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Stephan-S/FS19_AutoDrive#1118]
AutoDrive Version: 1.0.7.1
Release or custom zip: Release

2020-02-27 21:39 Error: Running LUA method 'update'.
2020-02-27 21:39 D:/FARMING_SIMULATOR/mods/FS19_AutoDrive/scripts/Utils/AutoDriveTrailerUtil.lua:620: attempt to index a nil value

**Comment by plexten** [comment]
Den Fehler hatte ich bei mir auch, da die Ballenanhänger als <vehicle type="Trailer"> in der Fahrzeug xml eingetragen waren. Dann hab ich es auf <vehicle type="dynamicMountAttacherTrailer"> geändert und der Fehler war weg.

**Comment by Iwan1803** [comment]
Dies wäre eine mögliche Ursache. Hätte er das Template mal komplett ausgefüllt, müssten wir nicht raten...

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
