### ISSUE TITLE
Truck towing a trailer does not fill up correctly from a conveyor

### ISSUE THREAD

**Issue by StuartLivings** [Stephan-S/FS19_AutoDrive#1141]
AutoDrive Version: 1.0.7.1
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable): D754 (mod) using HKD module (mod) with HKD (standard release) trailer

**Describe the bug**
I have set up conveyors to empty the manure into trucks.  The output of the conveyor is located at a suitable waypoint.

I then set trucks to pickup at the conveyor waypoint and drop off at the BGA.  A truck on its own operates correctly, filling at the conveyor and emptying at the BGA.  A truck with a trailer seems to fill just the truck.  This behavior is not reproducible for other fill sources (e.g. silos) where both the truck and the trailer fill correctly.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
