### ISSUE TITLE
Dedicated server don't save edits

### ISSUE THREAD

**Issue by chaze117** [Stephan-S/FS19_AutoDrive#1152]
**AutoDrive Version:** 1.0.7.2
**Release or Custom Zip:** Release  
**Map:** All  
**Vehicle / Type:**  Not Relevant
**Multiplayer or Singleplayer:** Multiplayer 

**Describe the bug** 
So when I edit the courses in the new ingame edit mode the server don't save any of the edits, no matter what I try. Tried save the game manually, export - import no use.

**If applicable - Steps to reproduce the behavior**  
Make some route on a dedicated server, edit with the ingame editor relog and the edit is gone.

**Comment by Jtrentcamp** [comment]
I also have the issue. After import: I'm able to see the way-points and the red editor bar follows the points where the green lines with arrows used to be.

**Comment by ddewar** [comment]
Same issue here. With both the new edit mode and with deleting nodes in the normal edit mode. Also noting, I have had this issue on dedicated server in older versions too.

**Comment by ddewar** [comment]
Has anyone found a workaround for this? I love using autodrive, but without being able to edit courses things are getting messy :)

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
