### ISSUE TITLE
Activate Courseplay at Destination

### ISSUE THREAD

**Issue by aletheist** [Stephan-S/FS19_AutoDrive#1158]
**Is your feature request related to a problem? Please describe.**
I'm really enjoying the farm automation mods, but there's a few clicks I think could be eliminated still. 
For example, being able to activate courseplay (to do fieldwork) upon arrival at a destination. 

**Describe the solution you'd like**
Is it possible to have a "activate Courseplay at destination" button added to the "Drive to destination" option?

**Describe alternatives you've considered**
I have tried using Courseplay's ability to follow the Autodrive network. I was able to get to the destination field and begin work, however, Courseplay did not correctly align to the fieldwork start point and when the combine got full it didn't stop. I reported this issue to Courseplay and got wontfix, that I'm using it wrong.

**Comment by Tensuko** [comment]
> 
> 
> **Is your feature request related to a problem? Please describe.**
> I'm really enjoying the farm automation mods, but there's a few clicks I think could be eliminated still.
> For example, being able to activate courseplay (to do fieldwork) upon arrival at a destination.


That depends on the Destination and how much space the Vehicle got to allign correctly when AD send the Command to start CP Driver, also in what Type and Mode... Preset CP Driver would be needed.


> **Describe the solution you'd like**
> Is it possible to have a "activate Courseplay at destination" button added to the "Drive to destination" option?


Might be possible, but CP got to implement that as well.


> **Describe alternatives you've considered**
> I have tried using Courseplay's ability to follow the Autodrive network. I was able to get to the destination field and begin work, however, Courseplay did not correctly align to the fieldwork start point and when the combine got full it didn't stop. **I reported this issue to Courseplay and got wontfix, that I'm using it wrong.**


I haven't found any Issue from you, can you show me the Issue ?
Actually since there is no such option to do this, you was indeed doing it wrong, as AD and CP are not able to work like that right now. :)

What I can tell you from CP side, we never wanted and I am sure we never want to make CP able to get into a 'one click and done' solution.
What maybe could be done is preset the CP Driver with Mode and Course and all settings you need, then Start AD Driver to a Field and then tell CP Start at 1st Waypoint, but got to talk about that with CP dev.

**Comment by aletheist** [comment]
>What maybe could be done is preset the CP Driver with Mode and Course and all settings you need, then Start AD Driver to a Field and then tell CP Start at 1st Waypoint, but got to talk about that with CP dev.

This is more or less my thought. I want to be able to tell AD to start driving to a destination. While it's driving, I'll set up my CP fieldwork course, options, etc. I just want AD to 'press' the CP "Drive course" button once it arrives/as it turns off.

>I haven't found any Issue from you, can you show me the Issue ?

I may have extrapolated too much from the response [here](https://github.com/Courseplay/courseplay/issues/5030). No insult was intended by opening this issue here, I just took it to mean this kind of stringing together work items wasn't a desirable goal to the CP team.
