### ISSUE TITLE
MP: cant see new created waypoints until i reconnect

### ISSUE THREAD

**Issue by AngeloMerte** [Stephan-S/FS19_AutoDrive#1160]
Hi,

ich habe die Version 1.0.7.2, also aktuell, bis auf das letzte French "Update". Ich spiele im Multiplayer. Wenn ich nun, wie gewohnt, Routen anlegen möchte, werden die Punkte zwar erstellt (rote Linie deutet auf die Punkte), ich sehe sie aber erst, sobald ich das Spiel neustarte. Woran kann das liegen?

Gruß

**Comment by AngeloMerte** [comment]
Kann das Ganze mittlerweile etwas eingrenzen. Wenn ich auf der Marsch 4fach komplett neu starte, bzw. die autodrive dateien ausm Savegame entferne, sehe ich ganz normal alles, was ich einfahre. Wenn ich aber ein Wegenetz z.b. von Holger ins Savegame schiebe, wird mir dieses auch ganz normal angezeigt. Wenn ich aber nun selber Routen anlegen möchte, wie bspw. für Produktionen/Hof etc., werden mir diese nicht angezeigt.

**Comment by AngeloMerte** [comment]
Hier einmal unsere xml, umbenannt in log zwecks uploadmöglichkeit. Vielleicht findet jemand ja darin schon den Fehler. Haben mittlerweile alles Mögliche ausprobiert, unser Savegame können wir ausschließen, da der gleiche Fehler auch in einem komplett neuen Spiel ohne jegliche Mods (ausser ad natürlich) auftritt. Anfangs alles gut, sobald wir die xml ersetzen, sehen wir das "neue" Netz und das Problem tritt wieder auf. Haben testweise auch ad 1.0.7.1 ausprobiert, ohne Erfolg.

[AutoDrive_NF_Marsch_4fach_oG_V1_5_config.log](https://github.com/Stephan-S/FS19_AutoDrive/files/4334243/AutoDrive_NF_Marsch_4fach_oG_V1_5_config.log)

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
