### ISSUE TITLE
Wrong side offset on tilted ground

### ISSUE THREAD

**Issue by RedMonster-HUN** [Stephan-S/FS19_AutoDrive#1165]
**AutoDrive Version:** 1.0.   
**Release or Custom Zip:** 1.0.7.2
**Map (If applicable):** Fenton Forest 4x map (1.50 ver.)
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Hi. I have experienced an issue using the combine following mode. If the combine stops on a tilted ground (sideways tilted) the truck (or tractor) doesn't adjust the side offset properly because of the bank angle of the ground. And this way the combine can not tip the grain into the trailer. It seems to me that the mod checks only the horizontal distance between the vehicles. Maybe you could use the vertical distance between the vehicles wheels (on one specified axle) to calculate the bank angle and also the proper side offset to the combine. 
I hope you will see it and you can solve this problem.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
