### ISSUE TITLE
AutoDrive lagging when trying to drvie to modded Silo

### ISSUE THREAD

**Issue by Phalanx380** [Stephan-S/FS19_AutoDrive#1167]
**AutoDrive Version:** 1.0. 7.2
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
when using auto drive to unload to Silo Mod called Grain Silo Set With
 Multifruit by Top Ace888 it lags a lot when AutoDrive tries to drive to or even past the silo
![Screenshot_284](https://user-images.githubusercontent.com/39988550/76694151-53defd00-66c3-11ea-8b27-adb541813560.png) this is the silo mod that it conflicts with

**Comment by Phalanx380** [comment]
i was able to video it. https://youtu.be/ntj684gwCIQ this is more light lag it has dead lock the game some times.

**Comment by Stephan-S** [comment]
Hey, could you please post the log.txt file when you just had this happen here?
That would probably save me the time of setting this scenario up for myself.
There are probably errors in there on every frame and the problem might be easy to solve when you show me these errors.
Thank you for your help :-)

**Comment by Phalanx380** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4333964/log.txt)

**Comment by Iwan1803** [comment]
Try to deactivate the collision detection.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
