### ISSUE TITLE
Mouse toggle without window

### ISSUE THREAD

**Issue by BloodyRain2k** [Stephan-S/FS19_AutoDrive#1169]
**AutoDrive Version:** 1.0.7.2
**Release or Custom Zip:** Release
**Map (If applicable):** All?
**Vehicle / Type (If applicable):**
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Before the ingame editor, the mouse toggle didn't do anything without the window, which back then made sense.
Now it works either way, which again, makes some sense, as the new editing allows the editing without the window but the mouse.

But it still is toggling while neither the window nor the edit mode are active, and that's annoying me a little bit. Mainly because I sometimes accidentally click my mouse wheel without meaning to and it reacting to that even though there's no point.
It can stay on if edit mode gets turned off, but it shouldn't turn on without either the edit mode or the window.

But regardless of this being considered, <3 you for making this!

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
