### ISSUE TITLE
Autodrive Combine mode collision

### ISSUE THREAD

**Issue by sdl112** [Stephan-S/FS19_AutoDrive#1174]
**AutoDrive Version:** 1.0.7.2
**Release or Custom Zip:** latest from today 
**Map (If applicable):** Muiltimap (others i haven´t tested)
**Vehicle / Type (If applicable): Harvester / Combine
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Since one of the latest versions, i keep getting head on collisions between Tractor and Combine/Harvester on regular basis. Happens with any Combine / Harvester and the Tractor. 
Especially when starting point from Tractor is ahead of position of combine. Also the tractor tries to go around the combine trough the fruit all the time. 

Is fruit avoidance working for Tractors at all? or just for combine?

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
