### ISSUE TITLE
Please write in english... Its not a german only game....

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#1188]
I see it a lot lately and its annoying me... I thought there was a new rule to post in english as best as u can?? Its not a german game, so writing in german is putting other 
nationalities aside...

**Comment by gec100** [comment]
Although it is not hard to click translate icon, search is impossible.

**Comment by RalfGorden** [comment]
ihr könnt doch genau von deutsch in englisch übersetzen

**Comment by Iwan1803** [comment]
The last "rule" said only, that the title should be in english.
Not everyone can speak English and not everyone can speak German, but there are translators.

**Comment by Michael170978** [comment]
@Bobster82  I support your comment but it is easier to explain an issue in German as in English. I can english but honestly i am not sure if the modder knows what i mean. And we all want that Autodrive run any bugs. As faster the issue is fixed as better  it is for all of us. But I can image to write  Suggestion/requests in english.

**Comment by Iwan1803** [comment]
Most modders and suppoters speak english as far as i know and some (like Stephan and me) german.
The problem is that some translations are so bad that you don't understand them. So it is better to write in english or german, if one that is your preferred or native language.
