### ISSUE TITLE
Combine level to unload with courseplay

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS19_AutoDrive#124]
Hello Stephan.
I believe many people like me is very happy to see your colaboration with Courseplay mod developers. I am using AutoDrive toghether with courseplay and so far it all works great. I only have one question for you.
Will you at any point make a way for vehicles on AutoDrive be able to set a fill level of the combine for them to start drive to combine?
Asking this because courseplay has that feature, when combine reaches a set level (i have it usually at 50%) the tractor/truck with trailer will move to combine to unload.
This is usefull in order to avoid time wasted with truck/tractor driving to combine only when combine gets 100% full and has to wait truck/tractor for unload.
Any plans to make this an option on autodrive?
Thanks in advance.

**Comment by fudoido** [comment]
Also, along with this question, will it be possible in future for truck/tractor follow combine while unloading?
At the moment i have to order combine to stop while unloading because truck/tractor does not follow discharge pipe, unless i am doing something wrong (have not yet see an option for that feature).
This would also save time while harvesting, so that combine keeps harvesting while unloading.

**Comment by Stephan-S** [comment]
This feature will most likely not make it into AutoDrive, since the Unloader is simply not designed to follow the tractor.
This open up many potential problems which is why I chose to only support unloading when the combine is stopped. I sacrificed perfomance for stability in this case.

Courseplay mode2 however supports this. So we might integrate AD's route to and from the field with CP's dynamic unloader in the future.
But no promises here :-)

Best regards,
Stephan
