### ISSUE TITLE
[BUG] No pickup at silo when using Pickup/Delivery mode.

### ISSUE THREAD

**Issue by Maarkreidi** [Stephan-S/FS19_AutoDrive#1316]
**AutoDrive Version:** 1.1.0.5 RC1  
**Release or Custom Zip:** Release  
**Map (If applicable):** Agrodage
**Vehicle / Type (If applicable):**  Tractor + Trailer 
**Multiplayer or Singleplayer:** MP

**Describe the bug**  
Pickup/Delivry Mode, the automatic pick up doesn't function at silo.
Tractor stop engine and just wait.
 I must press the R key and choose what i'd like to load to launch the process. 
The delivry work as intended when at destination. 

**If applicable - Steps to reproduce the behavior**  
Choose Pickup/Delivry mode
choose pick up destination 
choose delivry destination (different from pick up)
choose the fruit
Launch AD

**Screenshots**

**Comment by Maarkreidi** [comment]
I Deleted the old destination point and have redone another one at the same location.
Now everything is working.!! curious but it's fine.

Once again thank you for this great and powerfull mod.

I think you can close this bad ticket.

**Comment by dreyvn** [comment]
AutoDrive Version: 1.1.0.4
Release or Custom Zip: Release
Map (If applicable): Emerald Coast
Vehicle / Type (If applicable): Truck + Trailer
Multiplayer or Singleplayer: Single

Im having a similar issue. Truck/trailer will drive to silo, load, then pull forward just slightly and unload back into the pit. then it will proceed on to the destination empty. I am using the same routes, same locations, same equipment as before in all previous versions with no issues. Only since 11.0.4 have i experienced this problem.

**Comment by BloodyRain2k** [comment]
It should be noted that AD __must not__ pass the waypoint before the trigger touched the last trailer.
As soon as it's past the waypoint it considers itself 'loaded', independently of actually having loaded anything or not.

Not knowing this has given me a lot of issues in the past.
