### ISSUE TITLE
Cant save created waypoint and targets[BUG]

### ISSUE THREAD

**Issue by RENATERA87** [Stephan-S/FS19_AutoDrive#1322]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** ravenport  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  Sorry about the bad english
I started the map and start to create waypoints and targets with autodrive. When i finished, i`ve saved the game and closed FS19. later on i started the saved game and noticed that the waypoints and targets that exists on my saved game is only the ones that contains in the original downloaded file. all my created itens was deleted from the saved game. i manage to reproduce the error over and over again with the same results. i notice that the "AutoDrive_Ravenport_config" dont exist in the save game folder after i exit the game, it only exist in the backup save game file.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4456171/log.txt)

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Opa-Andre** [comment]
Please try to reproduce your problem just using the mods you need. I would just start with plain ravenport map and autodrive and remove all other mods from your mods folder. According to your logfile you have for example several modmaps in your mods folder, which are using scripts. And the logfile shows an script error trying to create the XML.. 

If the problem is gone, you can put the modfiles back, one after another. But please make sure that you are not having several maps in your modfolder...

**Comment by RENATERA87** [comment]
deleted all mods except AD and test adding mod by mod. everything running ok until now. i didnt included any map mod and the game its ok. thank you for the help.
