### ISSUE TITLE
Auto Drive Editor

### ISSUE THREAD

**Issue by BerndUwe** [Stephan-S/FS19_AutoDrive#134]
hai,

Ich habe mal ne frage wie genau benutzt man den AD Editor?

welche datei genau muss ich laden?

gibts da ein TuToRiAl? :)

ich nutzte die Flusstal XXL V2 map

mfg bernd

**Comment by alex2ruote** [comment]
When you create a course on a map, in the savegame folder a file is generated named for example AutoDrive_Felsbrunn_config.xml. That is the file that you must select with the Load Config button. The map is the pda file usually found in the map folder of the mod map, but you need to make a copy and change it in a png file that you can store in the AutoDrive Course Editor\src\mapImages folder.

I'd like a tutorial too though, for some reason I find difficult to work with the Porta Westafalica map.

**Comment by Stephan-S** [comment]
Hey @alex2ruote 

thank you for your answer to @BerndUwe 

Could you tell me though what kind of issues you have with the editor?

And I'm sorry, but I just didn't get around to making a tutorial video yet.
There is just so much else to do and the editor is certainly subject to some change and enhancements in the near future which would probably invalidate a video on the previous version..

If you figure out how to use all functions, feel free to publish a video and I will happily link to it :-D 

Best regards,
Stephan

**Comment by alex2ruote** [comment]
Hi Stephan
You've done a really nice job with this mod, I enjoy creating networks and I use it instead of Courseplay for all the driving around part.
The editor works quite well with different maps, but with the Porta Westfalica map I managed to see it correctly just once and I don't know why. The original pda file is 4096x4096 and it didn't work, so I reduced the size to 2048x2048 like other 4x maps like DonDiego. If I'm not mistaken you have to select the four times button before loading the map, it doesn't work afterward. As I said, it worked just once, now I can't even see the whole map, just a small portion, even though I went back to the game to refresh the courses and saved it. 
The editor is quite simple and self-explanatory, I would just add a text to the load Config window to explain where to find the required file. 
What I haven't figured it out it's how to associate a map to a config file like the ones already in the mapimages folder, because the editor doesn't remember the location of the last opened folder and it's quite tedious to search for it every time. A nice addition would be the possibility to see which points are destination points. 
Thank you for your work, it really makes a difference for single players who play with big maps.

Viele Grüße,
Alex

**Comment by Flyingfufu** [comment]
Hi there,
First of all, many thanks for this great piece of work. Well done !!!
Same issue here. I was able to open and make changes on the main map I'm using. All went fine as i could see the changes reflected in game. However, no way to open it anymore in the editor since, and same as for @Alex2ruote, only a very narrow band of the map is now appearing .
Any temp file that would need to be deleted to get it back working and avoid to recreate all ?

All the best !

**Comment by Stephan-S** [comment]
Could you send me your config files so I can open them and see what kind of errors are being thrown?
If it requires a special pda file, it would be great if you could also include it :-)
Thank you!

**Comment by Flyingfufu** [comment]
Hi Stephan,

 

Thanks for your prompt feedback. I’m primarily using the Goeddenstedt map. Attached you will have the latest config file still working ingame but not loading in the editor and the map pda.

 

Keep on doing your great job !!

 

Fabien

 

De : Stephan Schlosser <notifications@github.com> 
Envoyé : dimanche 26 mai 2019 10:16
À : Stephan-S/FS19_AutoDrive <FS19_AutoDrive@noreply.github.com>
Cc : Flyingfufu <fabien.fuster@sfr.fr>; Comment <comment@noreply.github.com>
Objet : Re: [Stephan-S/FS19_AutoDrive] Auto Drive Editor (#134)

 

Could you send me your config files so I can open them and see what kind of errors are being thrown?
If it requires a special pda file, it would be great if you could also include it :-)
Thank you!

**Comment by alex2ruote** [comment]
I got rid of the old config file and I'm almost done with redrawing a network on my map, everything works fine now. I still don't know how to automatically load a map though.

**Comment by Stephan-S** [comment]
Autoload isn't implemented for custom maps, but I will add this when I'm adding the destination editing support.

@Flyingfufu email attachments are not forwarded to me. Can you upload the data somewhere else?
Thanks again

**Comment by Flyingfufu** [comment]
@Stephan-S 

Please check following dropbox link and let me know if it doesn't work.

https://www.dropbox.com/sh/lxaxkjpypaxl7dv/AAAih_6qTPTNmdJ0uXc_7kcja?dl=0

**Comment by Stephan-S** [comment]
Hey, I could actually open and edit the file just fine.
But I just uploaded a new version of the editor which allows editing mapMarkers (destinations).
It also autoloads map files if they are in the same folder as the AD.jar file

Your Goeddenstedt map png is now already included.

Best regards,
Stephan

**Comment by alex2ruote** [comment]
I got rid of the old config file and I'm almost done with redrawing a network on my map, everything works fine now. I still don't know how to automatically load a map though.

> 
> 
> Hey, I could actually open and edit the file just fine.
> But I just uploaded a new version of the editor which allows editing mapMarkers (destinations).
> It also autoloads map files if they are in the same folder as the AD.jar file
> 
> Your Goeddenstedt map png is now already included.
> 
> Best regards,
> Stephan

Great Job Stephan, es funktioniert hervorragend!
Alex

**Comment by Flyingfufu** [comment]
First tests with the new editors are running flawlessly. All looking good so far !

Thanks a lot for this speedy fix!
Fabien

**Comment by Knowen** [comment]
Can someone tell me how this thing works? I load the config from the savegame folder and nothing happens. 
As someone mentions above to save the pda_map as a .png file into the mapimages folder..i also did that on nothing happens, when i load the config.

I dont want a video tutorial, just a quick step by step guide. That would be awesome!

FYI: I play on the Multimap2019

**Comment by alex2ruote** [comment]
With the new map autoload feature you should just rename the map so that it matches exactly the name embedded in the config.xml file. If you load a 4x map remember to click on the Four Times Map button before loading any file.

**Comment by Knowen** [comment]
@alex2ruote Thanks for the answer, but it doesnt work. In the config.xml file, located in my savegame folder, the map name is Multimap_2019. So i renamed the .zip file and the mapimage, to match that. 

First i click "Four Times Map" Button and then i load the config..nothing happend. Then i copied the AD.jar file in the same folder as the .zip file is. Start it all over and again nothing. 

What am i doing wrong?

**Comment by alex2ruote** [comment]
Only the png file should be renamed and put in the folder with the other ones for the Autoload function to work. You can put the folder named AutoDrive Course Editor wherever you want on your PC, it doesn't have to be within the savegame or the zipped mod map, but you must keep it as it is. If the map doesn't load automatically, open the editor, click the Four Times Map button, then load the config file first, then load the map. Sometimes you have to drag inside the map panel with the mouse to display it properly. Make sure that the png map size is 2048x2048, otherwise it doesn't work. 

You can write in German if you want, I'm just horrible at writing in it, but I understand everything.

**Comment by Knowen** [comment]
Okay, here is what i do now:

1. Click the Four Times Map Button
2. Load the config file
(Map doesnt load by itself so)
3. Load the map image (this is a .png file and 2048x2048)
4. Nothing...

I keept the AD Course Editor folder as it is. I removed nothing just added the map image. 
This thing drives me crazy 😠

**Comment by alex2ruote** [comment]
Have you tried with another map? Felsbrunn or Ravenport should work without a hitch.  Or you could start a new savegame with the same map and just draw a short course to test it. Make always sure to update the network before exiting the game. Maybe an error occurred with the config file, it happened to me and I had to delete it and start a new network. Can you upload the files for the multimap somewhere?

**Comment by Stephan-S** [comment]
Hey 
@Knowen if you can provide the files, I will try them out to see if they cause some bug in the ditor.
@alex2ruote Thanks for helping out here!

Btw: you can put your map file in the same folder as the AD.jar file. If it matches the map name in the config file, it will be loaded directly.

Best regards,
Stephan

**Comment by Knowen** [comment]
@Stephan-S Sure, just tell me what files do you need and i'll gibe them to you.
And which map file can be in the same folder as the AD.jar? The mapDE.i3d file?

**Comment by alex2ruote** [comment]
The editor works only with the png files, you can put them in the mapImages folder with the others. What Stephan probably meant is that the editor looks for a file in the main folder and the subdirectories. You can upload your png map file and the config file on Google drive and post the link here.

**Comment by Knowen** [comment]
[https://drive.google.com/drive/folders/1bMHaw1KTsWuI7wo0pkw-yI23mxl-YhFM?usp=sharing](url)

Here is my config and png file. Hopefully they will help you.

**Comment by alex2ruote** [comment]
Did you by any chance just rename the dds file to png? The problem is that the editor won't recognize the map as a png file. If you convert it properly it works without a problem, the autoload too. You need a converter or an editor like paint.net (free) to open the dds file and save it as a png file. 
Nice map BTW, I'm gonna keep it.
Tschüss
Alex

**Comment by Knowen** [comment]
Oh thanks god. Now it works! Thank you so much ❤️ @alex2ruote

**Comment by alex2ruote** [comment]
You're welcome, glad I could help.
