### ISSUE TITLE
Suggestion, improvements

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#141]
He Stephan
Thank you for ur autodrive mod, I really like the idea of it. Im a active courseplay user and do almost everything with it... Now i found out about this mod just yesterday... It really is my style of making routes, I really wanted that sort of system in courseplay.. Im playing around with ur mod and I must say its fun to play with! But it needs some adjustments to be great ;)
Thanks for ur effort for making this mod!

Here I have some suggestions/improvements what i like to see

It still need some finetunes like driveability in corners, vehicles seem to slow down pretty much in corners.
I like to see a drop down or list with stop points, scrolling trough the points when u have a lot is a bit annoying :P
Warning msg like vehicle arrived or stucked, I like to see them displayed until u select the vehicle (else i might forget they arrived :P )
Improvement for combine unloading (courseplay still does a better job)
*Maybe auto update network when finished recording... sometimes i forgot to update and I thought i did forgot to connect a route... lol
These are a few that came up now.

I hope you can find some good teamwork with courseplay team. Would be great if u guys can work something out to make it all even greater.

**Comment by Stephan-S** [comment]
Hey Bobster,
thank you for your extensive feedback.

Some feedback on your suggestions:

Driveability in Corners:
I will add this as issue. Currently AD breaks and accelerates at 100% in corners to get to the 'desired' speed. I will probably just adjust this value which should result in much smoother cornering.

Drop-down list:
Much requested now, but I still haven't gotten around to actually implementing it.
The advice I usually offer for now is to either bind the target selection to suitable buttons on your gamepad/wheel/joystick or if you are using the keyboard, to try out the auto-complete feature. Just click into the destination names and start typing. Auto-complete suggestions can be tabbed through with the tab key and accepted with the Return key.

Persisting warning messages:
I absolutely understand the desire to have this feature, but I personally don't want to implement it for now, as it sort of bloats the 'small' AD mod with features I personally don't really see as essential.
I'd like to keep the HUD and also the displayed messages as small and unobstrusive as possible. I only play with the minimal HUD of AD and only display the actual HUD if I have to make any changes to the network.

Combine mode:
Could you explain it in more detail? But yeah absolutely, CP's version is more advanced. I created mine in a hurry in about two weeks (on hobby time :-) ) and mostly because CP is not MP-ready and I wanted to use the mode on an MP-server as well as being able to use my road network.
And as you can see, the courseplay devs and I are trying to combine the best out of both worlds here, so stay tuned :-)

Best regards,
Stephan

**Comment by Bobster82** [comment]
Thanks Stephan for ur quick reply!
Let me know when u have something new here to test out. Im happy to do so ;)
Only Im going away for a week to germany (vacation ;) ) So after that I can test out again.

Thanks for ur great work so far!

**Comment by Bobster82** [comment]
I must say the driveability in corners is a lot better now.... only the "smaller" corners can be slow sometimes, but overall its better ;) (if you want to drive them perfect, you need to drive it yourself haha)
I also love the drop down menu for the waypoints and that they are in order ;) Thanks for that!

What i meant with combine mode is that ur way is pretty basic, you cant say when to drive to the combine (%full of the combine) and the route the tractor generates is a bit fluffy,, no straight lines and it takes too much time to get to a combine imo. Also the combine needs to be stopped before it works, costing a lot of "worktime" ;)

Ok, another "thing" i came accross is when 2 vehicles come to a crossing point, they colide almost every time... they dont give priority, they stand still together (no warning msg given)
And also an annoying thing is that when using courseplay mouse, it cant be used in autodrive and visa versa ... maybe something to combine?

Thanks for ur work, I really love it! Keep it up :D
