### ISSUE TITLE
[Feature Request] configurable waypoint markers (vehicle type, speed,...)

### ISSUE THREAD

**Issue by Jaiimez** [Stephan-S/FS19_AutoDrive#1493]
I have a few small suggestions for features I would love to see in Autodrive, and would love to see other peoples input.

1. Access only markers.
     Being able to assign a marker to a node (preferably at the start of a new 'road') to make the area between the markers access only, best example atm is on Sandy Bay, I would prefer vehicles to enter/exit the farm via the main front gates and follow the road, as the gradient is better for lower powered vehicles coming from that direction, but if I have a network path set for the gravel road that leads out the back of the farm, the route generator prefers to take them that route and up the extremely steep slope, but I want the network setup for that back path as I use it to access certain areas, but I would like to make it so that the route generator will only use that part of the network if the area it needs to access is within the access only markers.

2. Speed limits.
    This one is alot more self explanatory, being able to set specific max speed limits to certain parts of the network, I have all my vehicles currently set to a max of 29 to avoid the speed traps on Sandy Bay, but when it's in the main farm, i'd ideally like it to keep below 10, so being able to assign a start and end node, and routes between that node have a maximum speed of whatever is assigned, without having to keep an eye on where the vehicle is and change the maximum in the hud everytime it enters an area.

I've just attached a picture to explain a situation of what I mean, for example in the below picture, i'd like vehicles to only take this one way path my tractor is currently on, only if they're trying to get to the fertilizer tanks, anybody passing through that area of the farm i'd prefer to take the 2 way route to the north of the picture, but the generator prefers to take the one way path currently, which often has equipment or vehicles idling in the way.
https://prnt.sc/t8jc0z

The final little thing I was wondering, a way to access the route editor without being in a vehicle, sometimes making fine tuning ot the routes can be difficult with a big lumbering tractor.

**Comment by Iwan1803** [comment]
We have already had this request several times.
Both points would require a classification of waypoints/markers (vehicle type X may drive here, but Y may not, or speed points).
Sorry, but we will not implement this complexity, because the cost/benefit factor is simply not given.

Maybe there are other ways to solve your problem. By the way, blue lines are not always the best solution...

**Comment by ValokAsura** [comment]
Regarding request #1, would it be easier to allow a player to add a weight/penalty to a waypoint?

For example, you have a main traffic path adjacent to a 'parking' path+waypoint, but the shortest physical route is the 'parking' path so vehicles take it instead of the main path. My suggestion is when you create+name a waypoint, you could have a dropdown to add a distance penalty for the waypoint, say, +1000 meters. Then, when calculating a route, a vehicle will see the main path as being much shorter than the parking path.

The only game I've played with something like this is Rimworld, where you could add a penalty to a spot along a path to ensure they only go there as a last resort, or if all other paths are unavailable.

**Comment by Iwan1803** [comment]
What's the difference? We will not implement any classification for waypoints or targets.

However, there is already a setting to bypass target points and it is called "Maximum detour":
`Maximum detour when avoiding targets`
If it is set greater than 0 m, AD will drive around existing target points within that radius.

**Comment by Jaiimez** [comment]
I am very disappointed you feel this way, obviously I am not a programmer so I respect I don't have an understanding the amount of work that would be required to implement the suggestion, but I hope that maybe some time in the future, if others have suggested it you may reconsider, Autodrive is a superb mod and I sincerely hope it continues to develop and grow on it's own.

**Comment by Iwan1803** [comment]
It has been suggested several times, but the programming and support effort for that would be enormous.
Giving a waypoint or destination an attribute is a huge effort. The saving and reading routines would have to be adapted, but above all the path planning would have to be revised.
Afterwards we would probably have a lot of support if some vehicle doesn't drive as they should - especially if it's a mod.
I hope this makes it clear why, unfortunately, we sometimes have to say no

Maybe Giants will give LS2x roads and paths certain features and attributes that mods can react to.
