### ISSUE TITLE
combine unload problem

### ISSUE THREAD

**Issue by michal44001** [Stephan-S/FS19_AutoDrive#1593]
I have a problem with this mod , when I am harvesting the field the worker with AD don't see the combine he won't go to unload it , I made the point for example field 17 on the field and near the field but it 's the same problem he's staying and still see waiting for call. link to log screens. https://megawrzuta.pl/filesgroup/a0d3e85f14086de34ec95fcd1e05266b.html

**Comment by Iwan1803** [comment]
Which mod? Which map? Settings? Log?
I can't open your link and i tried it whith 3 different browser.

**Comment by michal44001** [comment]
Mod autodrive, map lubelska dolina from modhub, settings like on the yt tutorials, log is without errors and warnings I throw out mods with errors

**Comment by michal44001** [comment]
![log 1](https://user-images.githubusercontent.com/63665216/93493046-c7302880-f90b-11ea-8a9d-07388b174491.png)
![log2](https://user-images.githubusercontent.com/63665216/93493049-c8615580-f90b-11ea-9376-02959b4bfd28.png)
![log3](https://user-images.githubusercontent.com/63665216/93493053-c8615580-f90b-11ea-8244-b28de51e8e27.png)

**Comment by SteelRodent** [comment]
So not sure if this is the same issue, but I have this same problem with the latest versions of CoursePlay, where basically if CP is driving the combine, AD won't unload it. Even if I disengage CP when the combine is full, AD still won't come to empty it. I got nothing whatsoever in the log of note.

**Comment by SteelRodent** [comment]
I have the same (or similar) issue with CP and AD since a few months. CP driving the combine, AD set to unload, but AD refuses to unload the combine. Even when I have CP set to self-unload the combine, despite the AD tractors reaching 100% full, they still just sit there and won't go unload. Oddly enough, it still works like it's supposed to when harvesting potatoes - with CP harvesting and AD unloading (not perfect, but it does work). Using AD in pickup & deliver mode seems to be the only way it works with CP atm.

**Comment by michal44001** [comment]
I have changed the map 2 times its better probably this map is shit conflict with straw harvest and AD, if anybody has more ideas for problem writr comment

**Comment by Axel32019** [comment]
No update -> Closed.
