### ISSUE TITLE
[BUG] Pickup and deliver cycle - vehicle does not stop during unloading (1.1.0.5-RC6)

### ISSUE THREAD

**Issue by Dennizzzzz** [Stephan-S/FS19_AutoDrive#1612]
**AutoDrive Version:** 1.1.0.5-RC6   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Yesterday upgraded AD from RC5 to RC6. I have two animal food destinations in a map. Set vehicles 'Cycle Pickup and Deliver' to 'Pickup and Deliver'.  Now the driver does not stop at the unloading points feeding my animals. It starts unloading but keeps on driving (trailer is not empty, and troughs are not full). 

After only changed back from RC6 to RC5, there is no problem.

**Screenshots**  
Setting:
![image](https://user-images.githubusercontent.com/10248136/94259622-117a6080-ff2f-11ea-8e73-b9c51155dcde.png)

Course at one of the trough where it works with RC5 but not with RC6
![image](https://user-images.githubusercontent.com/10248136/94259632-15a67e00-ff2f-11ea-82fc-2843e7a678f2.png)

**Comment by Iwan1803** [comment]
If you are using Courseplay, try the latest or an older version (040).

**Comment by Dennizzzzz** [comment]
> 
> 
> If you are using Courseplay, try the latest or an older version (040).

Sorry, not sure what you mean. I'm not using CP for this. Only AD to feed the animals. Added multiple destinations in a AD folder, and setup AD to 'Pickup and Deliver', so it cycles thru the destinations in the folder. The vehicle is not stopping at the destinations point to unload the trailer. It just drives on.

**Comment by Iwan1803** [comment]
If CP is in the mod folder, it could cause such problem.

**Comment by ark471** [comment]
Hallo Iwan1803,
ich hatte dieses Problem im Modus Rotierend Be- und Entladen: nur Entladen auch festgestellt und wollte es schon posten. Habe es auf der Oberthal nur mit Autodrive und GlobalCompany im Mod-Ordner getestet. Das Fahrzeug kommt bis vor den Trigger, fängt an abzuladen, bleibt aber nicht komplett stehen sondern rollt dabei langsam weiter bis zum Trigger-Punkt und fährt dann weiter.
Da ist irgend etwas nicht in Ordnung! An Courseplay kann es nicht liegen.

I had detected this problem in rotating loading and unloading mode: only unloading and wanted to post it already. tested it on oberthal only with Autodrive and GlobalCompany in the mod folder. The vehicle comes up to the trigger, starts to unload, but does not stop completely, but slowly rolls on to the trigger point and then continues.
Something is wrong! It can't be because of Courseplay.

Grüße

Ark

**Comment by Iwan1803** [comment]
Das Phänomen hatten wir gestern auch und da war VCA dran Schuld. Nutzt du das?

**Comment by ark471** [comment]
Nein habe VCA nicht mit drauf. Wie gesagt, zum Testen auf der Oberthal nur mit Autodrive und GlobalCompany im Modordner trat der "Fehler" auch auf. Beim Bestücken der Gewächshäuser mit Kompost beim Rotieren im nur Entladen-Modus.

**Comment by Dennizzzzz** [comment]
Also if I only changed back from AD version RC6 to RC5 the problem is not there anymore. So whatever mods I use, if I only update AD, my conclusion would be than it is a problem of AD. Or is the code of RC6 changed that much from RC5 that other mods can influence AD?!

**Comment by Dennizzzzz** [comment]
@Axel32019  Is there a way to get a 'nightly' build or something? Really like RC6, but not without the fix you created :-)

**Comment by Axel32019** [comment]
@Dennizzzzz Short copy & paste:
https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing

Code -> Download ZIP
Extract the downloaded zip "FS19_AutoDrive-beta-testing.zip"! Do not put it into the mod folder, this will not work !!!
In the extract you find the folder "FS19_AutoDrive" -> zip and put to mod folder -> start the game

Code -> Download ZIP
Die herunter geladene zip-Datei "FS19_AutoDrive-beta-testing.zip" auspacken! Nicht in den mod Ordner verschieben/kopieren, das funktioniert nicht !!!
In der entpackten Datei den Ordner "FS19_AutoDrive" neu als zip packen -> zip in mod Ordner kopieren -> Spiel starten

**Comment by Dennizzzzz** [comment]
Great to see this fixed !
