### ISSUE TITLE
Parking with implement attached[BUG]

### ISSUE THREAD

**Issue by Penduras** [Stephan-S/FS19_AutoDrive#1693]
**AutoDrive Version:** 1.1.0.6   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**  Tractors and trucks
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I have a parking spot selected, and it's working, but as soon as i attach an implement or trailer, the parking button is greyed out, and have to assign new parking spot. Not sure if a bug, or intended

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Anonymous-any** [comment]
Hello sure not !! I don't understand why you set this as bug rather than a question ?
You right, the gray become when attached thing the 1st time. That show you there no Park place attributed to the one attached !
After it has set a park place it's ok. That mean too you can set a park place to each and every tools you have.
Some example:
https://www.youtube.com/watch?v=l2yTUbMSKPM
https://www.youtube.com/watch?v=2ftbKW9kB0k
Remove bug plz !

**Comment by Iwan1803** [comment]
FYI: a parking space can be assigned to attachments only in singleplay, not in multi or on a dedi server.
If you don't have any question, then please close the issue.
