### ISSUE TITLE
Editing waypoints  (bug?)

### ISSUE THREAD

**Issue by Alexander-ux** [Stephan-S/FS19_AutoDrive#1784]
Don't know if this is a bug or my settings:
If i want to create a chain of wp by holding CTRL and clicking LBM i can't start from a existing wp.
Starting a new chain works just fine.

also..
I can create a chain of  light blue wp by holding both LCTRL and LSHIFT + LMB. Dont know if this was unintended from the coders , but it would be nice if there was an option for making blue lines to..  :-)

**Comment by Axel32019** [comment]
Hello @Alexander-ux , You are right with the starting point.
For the creation and usage/meaning of the lines you may have a look here: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode

**Comment by Alexander-ux** [comment]
@Axel32019 , So is this a reported bug? (not everything is in english so..)
Or is this the way its going to be ? In 1105 this was not an issue.

and the instructions you are refering to ? 
Creating light blue lines like I explained is not on this page. and creating blue lines is neither.  so..

**Comment by Axel32019** [comment]
@Alexander-ux Sorry, but can't follow you. The wiki explains the different lines:
blue line = two way / light blue line = backward
What do you mean?

**Comment by Alexander-ux** [comment]
@Axel32019 
I did not ask the meaning of the colors.
suggest you read my comment a couple more times..

**Comment by TyKonKet** [comment]
Hi @Alexander-ux, with 8acbad0108a8a74e13f808752617aca303861622 I've added the ability to start "chaining" from an existing wp, you can now (while you are holding LCTRL) select an existing waypoint so that when you will create the first new wp of your "chain" they will be connected.

> I can create a chain of light blue wp by holding both LCTRL and LSHIFT + LMB. Dont know if this was unintended from the coders , but it would be nice if there was an option for making blue lines to.. :-)

That would be very useful, but to actually I just don't know what button to use for this feature.
Currently I think we should rewrite from the ground the editor to make much easier for the future to add new features, so you will probably see that feature in the next months as part of a bigger update of the extended editor.
