### ISSUE TITLE
It crashes in MP release 2.5

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#179]
With the last release, on Dedi server, it happened that, everything seemed to work, but as soon as I tried to modify a path, I noticed immediately that, to cancel some points, it took a long time, then suddenly it stopped everything, and has corrupted the game, now you enter it, after less than a minute, it stops. Checked in the Log, but there are no errors related to the AD, and putting back the 2.4, loading a backup savegame, of the day before, everything starts working again .....
Starting the corrupt savegame, on my PC in MP mode, to me. that I'm Host, it works, while my other friends, crash. and even here I see no errors in the Log ... :(

**Comment by Stephan-S** [comment]
Hey,
modifying courses in MP has always been a bit 'slow' because AD is trying to synchronize after pretty much every change you make to the 'old course', which especially includes deleting waypoints!

Just a short example of what happens when you remove node e.g. 347:
Before:
Nodes: 1,2,3,...,346,347,348,...7590,7591 (or how ever many points you have :-) )
After:   1,2,3,...346,347 (previously called 348), 348 (previously called 349), ... 7590 (previously 7591)

So every point after the deleted id has to be 'touched' and then the whole network is redistributed to all clients.

But anyhow, I am suprised that there are no errors in the log. Did you have access to both the server(host) log and the client log file? I would really like to solve this one.

Can you send me the corrupted savegame?

Best regards,
Stephan

**Comment by Roby1164** [comment]
In summary, I was deleting a point, and the game crashed, without giving errors in the Log, from that moment, whoever came in, after a few seconds, stopped.
Trying the same savegame locally, in MP, works, even trying to modify other points.
Now I have saved and as soon as possible we put it back on the Dedi server (I have to wait for my friend who is off for the weekend) and let's see if it works, given that for me, the problem is in writing to the change server .... maybe it uses too long, and time out the procedure, but causing the players to crash, which in local MP doesn't happen ...

**Comment by Roby1164** [comment]
I was not able to deal with the problem, given that, having taken the savegame from the server, started on my PC in MP, everything works, no block, now saved, reloaded on the server, it magically works !!!
In my opinion, the problem is in writing the file, when the paths are changed, and for unknown reasons, the server dedi, finds it difficult to do the job, going to block.
