### ISSUE TITLE
wrong parking position after courseplay

### ISSUE THREAD

**Issue by blackscorpion80** [Stephan-S/FS19_AutoDrive#1812]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Traktor mit Anbaugerät

Nach Feldarbeit mit cp fährt der Traktor zu seiner Parkposition und nicht zu der Parkposition des Anbaugerätes. Anbaugerät war ausgewählt, nicht der Traktor.
Screenshot 1 ist kurz nach dem beenden von cp und bei Screenshot 2 hatte ich ad ausgeschaltet und manuell auf "P" gedrückt und ad hat den Parkplatz für das Anbaugerät angefahren.

![Screenshot 1](https://user-images.githubusercontent.com/79168434/108115788-e5f14180-709a-11eb-9c6e-456500e082e1.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/79168434/108115798-ebe72280-709a-11eb-9085-e36b7dd8d806.jpg)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Bobster82** [comment]
Hello,
With google translate its hard to understand it precisely. If im correct, your problem is: Courseplay wont go to the parking spot of the attachement, instead it goes to the vehicle parking spot? If so, this is because CP only works with the parkingspot from the vehicle (for now), not the attachement. Ask the CP def team if they can support in this "issue"

**Comment by blackscorpion80** [comment]
Yes that's right.  Thanks for the answer. Then this bug report can be
closed.

Bobster82 <notifications@github.com> schrieb am Mi., 17. Feb. 2021, 13:09:

**Comment by Axel32019** [comment]
This is not a CP issue. The park interface between CP and AD is some days old and therefor do not take care of the new park feature in AD.
To solve this some more informations are required (which I do not know yet):
- The park position is selected on activation of AD, with the selected vehicle or attachement
- During CP job AD not active, hence no park position is known
- If CP change the selected tool and / or vehicle during it's job(s) this will result in different park positions

So need some time / support for investigation...

**Comment by Bobster82** [comment]
> This is not a CP issue. The park interface between CP and AD is some days old and therefor do not take care of the new park feature in AD.
> To solve this some more informations are required (which I do not know yet):
> 
> * The park position is selected on activation of AD, with the selected vehicle or attachement
> * During CP job AD not active, hence no park position is known
> * If CP change the selected tool and / or vehicle during it's job(s) this will result in different park positions
> 
> So need some time / support for investigation...

Im sorry... thought it was cp that could only select the vehicle to park. 
You understand the code much better ;) and I didnt check what was coded at all... maybe im gonna dive into it and learn a bit more. Thanks Axel

**Comment by Bobster82** [comment]
> This is not a CP issue. The park interface between CP and AD is some days old and therefor do not take care of the new park feature in AD.
> To solve this some more informations are required (which I do not know yet):
> 
> * The park position is selected on activation of AD, with the selected vehicle or attachement
> * During CP job AD not active, hence no park position is known
> * If CP change the selected tool and / or vehicle during it's job(s) this will result in different park positions
> 
> So need some time / support for investigation...

@Axel32019 ,
I've been checking how this parking is working in AD and CP.. maybe this info helps out? 

* CP calls: self.vehicle.spec_autodrive:GetParkDestination(self.vehicle) to get the Park pos.
* AD returns the park pos from the statemodule: return self.parkDestination,  this is only from the vehicle. 

![image](https://user-images.githubusercontent.com/47780758/108381151-d4797800-7207-11eb-9307-33b47ac8a865.png)


To get the "active selected" parkDestination, AD uses AutoDrive.getActualParkDestination(vehicle) in AutoDroveUtilFuncs.lua .
But this only returns the right number when ur in the vehicle, else its returning a standard value (-1)

![image](https://user-images.githubusercontent.com/47780758/108386526-03461d00-720d-11eb-864f-34a94c4d76e1.png)


So my idea:
Make use of the self.parkDestinationAtJobFinished variable and return this value instead of self.parkDestination.
Set that value everytime when we switch between active vehicle or the tool... (if thats posible)

Am I at the right direction? If yes, do you need more from me? If not, O well, I tried ;) .. maybe a point in the direction ;)

**Comment by Axel32019** [comment]
@Bobster82 Thanks to support!
Your investigation is going in the right direction - checked!
The question(s) now are:
- If CP change the selected tool and / or vehicle during it's job(s) this will result in different park positions

Which part of the vehicle+attachment(s) are selected when CP has finished / pass over to AD?

**Comment by Bobster82** [comment]
@Axel32019 , 
Glad to help.

CP doesnt change the selected tool or vehicle during his work or refilling for what ive seen (Just did a few tests). As far as I know tools/vehicles are adressed directly and arent depended on "active selection" only AD uses it for parking.

**Comment by Bobster82** [comment]
@Axel32019 ,

I sometimes cant express myself good enough whats inside my head, so I try my best (and short as posible)

So Ive been diving into this as best as I could... was a struggle to get CP the right parkingspot as in the end, AD forces to use the parkdestination when its start driving. 
I had made so parkatjobfinished variable (with the selected tool) was passed to cp instead of the parkdestination.
With the last step, I saw in ExternalInterface.lua, there are 2 functions doing almost the same. I dont know what other mods besides CP uses those functions? Else might be easier to trim those down to a simple 1.

But 1 problem that cant be due a giants "bug" having to select the vehicle when a tool is attached. So when there is a tool, you automaticly park to the worktool park destination. 
I dont know what you guys want with this? I like the idea to park my tools over the vehicle when attached... when tool is parked, you can park the vehicle to his own spot.

All codes Ive changed didnt brake, but its messy :P 

Can u make something out of this? If you need something from me, let me know.


-- Bobster

**Comment by Axel32019** [comment]
@Bobster82 You may use the beta-Version to test:
- parkDestinationAtJobFinished  is set on vehicle/tool selection - thanks for this hint!
- AD now use parkDestinationAtJobFinished defined in selected vehicle/tool, in case not vehicle will stop and throw a message for missing park position

**Comment by Bobster82** [comment]
I wil check it out later today and let u know ;) 
Thanks for the help
