### ISSUE TITLE
[Feature Request] Non-Functional Feature Collection

### ISSUE THREAD

**Issue by Axel32019** [Stephan-S/FS19_AutoDrive#1820]
Collection of nice-to-have features in AD

Ligths

1. time frames to enable independend of map, Giants standard setting
    1 setting
2. situation: 
    - before trigger, inside bunker silo -> worklight front, if reverse -> worklight back
        1 setting
    - turn lights
        1 setting already in
    - warning lights while reverse drive
        1 setting
    - on street (no field)
        1 setting
    - on field
        1 setting
    - beacon lights
        1 setting already in
    - weather condition
        1 setting

**Comment by jtsage** [comment]
Additional situation: rain is falling (CP apparently does it, or at least did on the map I was playing yesterday).  Maybe snow too?

**Comment by Axel32019** [comment]
Hello @jtsage , Did I understand it right that you wanted to try to implement this, or not?

**Comment by jtsage** [comment]
Yes, I am interested in doing so, or at least helping out as best I can. Time is currently conspiring against me getting anything done though.

**Comment by jtsage** [comment]
Ok, so, did some digging today - this is the headlights bit. I'd like to document what I have at this point: (note - all values from either the debugger or GDN, specifically, all the fun is here: https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=32&class=368)

From scripts/Specialization.lua - comments added by me.
```lua
function AutoDrive:updateAILights(superFunc)
    if self.ad ~= nil and self.ad.stateModule:isActive() then
        -- If AutoDrive is active, then we take care of lights our self
        local spec = self.spec_lights
        local dayMinutes = g_currentMission.environment.dayTime / (1000 * 60)
        local needLights = (dayMinutes > g_currentMission.environment.nightStartMinutes or dayMinutes < g_currentMission.environment.nightEndMinutes)
        if needLights then
            -- It is night-time, the lights should be on
            local x, y, z = getWorldTranslation(self.components[1].node)

            -- The lights are *not* set to the aiLightsTypeMask, we are on the field, set them to that mask
            if spec.lightsTypesMask ~= spec.aiLightsTypesMask and AutoDrive.checkIsOnField(x, y, z) then
                self:setLightsTypesMask(spec.aiLightsTypesMask)
            end

            -- The lights are not set to a mask of "1", we are off the field, set them to mask "1"
            if spec.lightsTypesMask ~= 1 and not AutoDrive.checkIsOnField(x, y, z) then
                self:setLightsTypesMask(1)
            end

        else
            -- It is *not* night, turn them off if they aren't already off.
            if spec.lightsTypesMask ~= 0 then
                self:setLightsTypesMask(0)
            end
        end
        return
    else
        superFunc(self)
    end
end
```

### Light TYPES

So, light types via giants are, "officially"

* __0__ : Front Lights - in reality, standard Headlights
* __1__ : Back Work Lights
* __2__ : Front Work Lights
* __3__ : Headlights - in reality, brights

### Light STATES

That covers **light TYPES**. Of course, lots of mods use them differently - in order for the lights to work pretty in game, giants provides us with this xml (from one of the stock case magnum's

```xml
<lights>
     <!-... ->
    <states>
        <state lightTypes="0" />
        <state lightTypes="0 1" />
        <state lightTypes="0 1 2" />
    </states>
    <!-... ->
</lights>
```

These tell the engine what to do with each press of the "F" key (default binding).  First time, it'll turn on light type 0, second time, it's types 0 & 1, etc..

This information is available to us in the function above, it's currently in "local spec", "spec.lightStates" - stored as a table - please pardon the pseudo-code, still working on learning LUA.

```
spec.lightStates.1.1 = 0
spec.lightStates.2.1 = 0
spec.lightStates.2.2 = 1
```
etc..

### What is aiLightsTypeMask?

It's configurable actually, on a per vehicle basis - from GDN:
```lua
    local lightTypesStr = Utils.getNoNil(getXMLString(self.xmlFile, "vehicle.lights.states.aiState#lightTypes"), "0 1 2")
    local lightTypes = {StringUtil.getVectorFromString(lightTypesStr)}
    local lightsTypesMask = 0
    for _, lightType in pairs(lightTypes) do
        lightsTypesMask = bitOR(lightsTypesMask, 2^lightType)
    end
    spec.aiLightsTypesMask = lightsTypesMask
```
So, it's either ```<lights><states><aistate lighttypes=""></states></lights>```, *or*, the default of 0, 1, & 2

__suggestion__: it appears the mod can set this however makes sense, we should assume good intentions and only deal with the off-field setting?

### SUGGESTION / TO INVESTIGATE
we should set the user preference to be one of these states.  i.e., I want the "second press of the light key" to be my off-field light set. But, is this information available in the preferences GUI - I don't know yet.  Some vehicles have 3 light states, some have more or less - we can trap for invalids, but it would be a lot cleaner to get the possible states right the first time. (or, maybe it's easier to just to a pick box and fall back on a sane default like is done now?).  My next port of call will be to debug the GUI AD preferences and see just what is available there, as I have no idea.

This is also, in spec, a "spec.currentLightState" which is the currently enabled light state. Near as I can tell, it's information only - but if *this* is available in the settings GUI, would it be worth exploring "set your lights how you want them, hit settings, hit a button to 'save' it"?

### Setting the actual light state - bitmask vs decimal
Reference: https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=32&class=368#setLightsTypesMask4817

For what it's worth, setLightsTypeMask will happily accept a decimal representation of the light types, if that's easier in the long run.  It will happily accept (and silently discard) a light type mask that refers to lights that don't exist too - it runs through the lights that actually exist on the vehicle, then bitAND's the mask given to it. I wouldn't push it, but probably anything under maxint wouldn't be a problem - depends on what bitAND() implementation I suppose.

Also, aiLightsTypeMask is internally a decimal number - it's types 0,1, & 2 == 7

snip:
```lua
        local function getIsLightActive(light)
            local lightActive = false
            for _, lightType in pairs(light.lightTypes) do
                if bitAND(lightsTypesMask, 2^lightType) ~= 0 then
                    lightActive = true
                    break
                end
            end
```

Quick reference, should it be needed, and because I'm always bad at this:
<table>
<tr><th>Binary</th><th>3 - Brights</th><th>2 - Rear</th><th>1 - Front</th><th>0 - Headlight</th><th>Decimal</th></tr>
<tr><td>0000</td><td></td><td></td><td></td><td></td><td>0</td></tr>
<tr><td>0001</td><td></td><td></td><td></td><td>*</td><td>1</td></tr>
<tr><td>0010</td><td></td><td></td><td>*</td><td></td><td>2</td></tr>
<tr><td>0011</td><td></td><td></td><td>*</td><td>*</td><td>3</td></tr>
<tr><td>0100</td><td></td><td>*</td><td></td><td></td><td>4</td></tr>
<tr><td>0101</td><td></td><td>*</td><td></td><td>*</td><td>5</td></tr>
<tr><td>0110</td><td></td><td>*</td><td>*</td><td></td><td>6</td></tr>
<tr><td>0111</td><td></td><td></td><td></td><td>*</td><td>7</td></tr>
<tr><td>1000</td><td>*</td><td></td><td></td><td></td><td>8</td></tr>
<tr><td>1001</td><td>*</td><td></td><td></td><td>*</td><td>9</td></tr>
<tr><td>1010</td><td>*</td><td></td><td>*</td><td></td><td>10</td></tr>
<tr><td>1011</td><td>*</td><td></td><td>*</td><td>*</td><td>11</td></tr>
<tr><td>1100</td><td>*</td><td>*</td><td></td><td></td><td>12</td></tr>
<tr><td>1101</td><td>*</td><td>*</td><td></td><td>*</td><td>13</td></tr>
<tr><td>1110</td><td>*</td><td>*</td><td>*</td><td></td><td>14</td></tr>
<tr><td>1111</td><td>*</td><td></td><td></td><td>*</td><td>15</td></tr>
<table>


### Other things I found in there:

spec.turnLightState is current turn signals - I had the hazards on and it was "3"

spec.numLightTypes looks like an index of the light types that exist, it's "4" on the mod I'm using, 0,1,2, & 3 all exist.


More to follow.

**Comment by jtsage** [comment]
Borrowed from courseplay, this is how they are turning on the lights for rain - real simple.

```lua
function AIDriver:shouldLightsBeUsedForEnvironment()
	-- How Giants decides lights in Lights:updateAILights
	local dayMinutes = g_currentMission.environment.dayTime / (1000 * 60)
	local nightTime = (dayMinutes > g_currentMission.environment.nightStartMinutes or dayMinutes < g_currentMission.environment.nightEndMinutes)
	local rainScale = g_currentMission.environment.weather:getRainFallScale()
	local timeSinceRain = g_currentMission.environment.weather:getTimeSinceLastRain()
	local raining = rainScale > 0

	local shouldLightsBeUsed = (nightTime or raining)

	return shouldLightsBeUsed
end
```

**Comment by jtsage** [comment]
Next bit - reverse driving lights. 

So, the reality is, I got this to work pretty easily - *however*, most of the stock vehicles do not actually have reverse warning lights.  So, should I explore using the rear worklights for backing up? And if so, should this be a per-vehicle configuration, as it is likely to be the wrong choice on some modded vehicles (any that use lightType=1 for something else).  I have a number of commits ready to be looked at, so far implemented:

* Daytime running lights - per vehicle, uses light state "1" (the first press of the light key), whatever light types that might be configured for
* Off-field lights configuration - per vehicle, you can choose what state you want - i.e. "1" would be a single press of the lights key, "2" would be a double press, etc.  I guessed that 5 was a good max (I've never seen more than 4), and if you choose one that does not actually exist, it will just use the first one, or failing that, lightType=0 only.
* Weather based headlights, global option, uses on field / off field light state selection from above (on field is still using aiLightsTypeMask - seems to be the best option, as it appears that this can be set by the mod to be the "right" selection)

**Comment by jtsage** [comment]
Ok, also added to my fork:

* Set times of day for lights off and lights on.
* Hazards off-field per-vehicle config

Fwiw, fork here, I will prepare a pull request soon, but would it be more or less helpful to do these features atomically?

**Comment by jtsage** [comment]
Final bit, and where I need help:

* Lights on before trigger - is there a section / place in the code where I can look at how AD knows it's approaching a trigger?  A utility function maybe?  And what criteria for this - lights on when approaching a fill trigger only when the vehicle is going to use it?

* Lights for the BGA - i found AutoDrive.isVehicleInBunkerSiloArea(vehicle) but it looks like that will only return useful (to me) results if the vehicle is actively filling the bunker.  It wouldn't help for unloading if I am reading this correctly.

Thanks much!

**Comment by jtsage** [comment]
![VehicleSettings](https://user-images.githubusercontent.com/605986/133183886-5e64c8e9-9b8a-42cc-a855-abfea8d5a71e.png)
![MainSettings](https://user-images.githubusercontent.com/605986/133183907-0bf4dda1-6f0e-4bc8-813a-a81049f64229.png)

## Where I'm At

### Per-Vehicle

* __A__ : Daytime running lights - turn on the standard headlights (state 1) when not on the field for this vehicle
* __B__ : Off Field State - at night, or in (optionally) bad weather, use this light state for this vehicle - corresponds to how many times you would hit the "lights" key when driving yourself.
* __C__ : Hazards Off Field - when not on the field, turn on the hazard lights (both turn signals).  Overrides/disables blinkangle for this vehicle (unless it's on the field)

### Not Per-Vehicle

* __D__ : Inclement Weather (renamed since I took the screenshot) - turn on lights if it's raining or snowing - respects on field / off field state
* __E__ : Override the time of day at which headlights are turned on - can be set from 16:00 / 4:00pm -> 23:30 / 11:30pm in half hour increments
* __F__ : Override the time of day at which headlights are turned off - can be set from 00:30 / 12:30am -> 10:00 / 10:00am in half hour increments

Of note, __E__ & __F__ are just a list of integer minutes - the list of options could be as long as is practical.  Another option would be a third option to *always* use lights, if that's something folks would want.
