### ISSUE TITLE
[BUG] No Waypoints after Restart

### ISSUE THREAD

**Issue by jk2345** [Stephan-S/FS19_AutoDrive#1946]
**AutoDrive Version:** 1.1.0.7   
**Release or Custom Zip:** Release  
**Map (If applicable):** Eiersholt  1.0.1.0
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  
  
Played a few hours, saved without Problems and after restarting the game I cannot see (and change) the Waypoints anymore.
Autodrive itself works.
In the log File I can see a lot of lua:504 Errors.

Log File is attached.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6595948/log.txt)

Best regards

**Comment by Stephan-S** [comment]
There seems to be an issue with one of your AutoDrive destinations.
Could you upload the AutoDrive_Config file from your savegame please?
Better yet, check in on our Discord, so we can deal with it over there: https://discord.gg/9D4B5hX

But since we have already released version 1.1.1.0 here on Github, I'm confident that the root cause for this bug is already found and fixed.

**Comment by jk2345** [comment]
Hi Stephan,
Thanks for your support.

I have seen after reporting the "BUG" that there is already a newer Version available and I have updated it.
Until now the Error did not happen again.

Anyway please find the Config attached.
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6602828/AutoDrive_config.txt)

Best regards
