### ISSUE TITLE
pickup/refill mode to startpoint[BUG]

### ISSUE THREAD

**Issue by mrPassion78** [Stephan-S/FS19_AutoDrive#1947]
**AutoDrive Version:** 1.1.1.0  

Sins the latest release, AD will not leave the field to refill the lime spreader when empty.
it says, cannot calculate path.
It happend on some of the fields and not on all of them. 
The funniest thing i noticed is when the tractor ITSELF is still IN the field that does not work, it says cannot find path, but when i move the tractor 2m to outside of the field, it works fine, with the same waypoint selected all the time ( see screenshots )

I will drop my log in here to, sins i really have no clue what this might be.
I checked all the exits of the fields, and they are fine.

Also , in all other modes the tractors goed to the selected waypoint without any problem.

I had to rollback to version 1.1.0.8 , and everything works just fine like it should. no more problems.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6602493/log.txt)
![fsScreen_2021_06_05_13_33_55](https://user-images.githubusercontent.com/40406761/120890621-50a39a00-c604-11eb-9279-8389f7029697.png)
![fsScreen_2021_06_05_13_34_04](https://user-images.githubusercontent.com/40406761/120890623-526d5d80-c604-11eb-9546-8f92a5e00fd9.png)

**Comment by Stephan-S** [comment]
Hey, the difference between on the field and off the field is, that when activated on the field, AutoDrive will invoke a pathfinder algorithm to try and find a path off that field, towards the network (based on field exit strategy in the vehicle settings).

However, I noticed a small issue in the code. If the vehicle is already so close to the network, it should just start driving along the expected path instead of using the on field pathfinder for these few meters.
A fix will be included in the next release.
Thanks for the report!
