### ISSUE TITLE
[BUG] AD only opens fertilizer cover with a seeder with multiple coves.

### ISSUE THREAD

**Issue by jobyrns72** [Stephan-S/FS19_AutoDrive#2013]
**AutoDrive Version:** 1.1.1.4   
**Release or Custom Zip:** Release  
Oklahoma 4x
arm JD 8350  
 Singleplayer:

Hello I have come across a seeder that will only open one cover while going through the trigger detection area. When going through the seed trigger it will try to shut the cover and open the other for a split second and thats it. It will only fill with dry fertilizer. If i drive manually through either trigger the corresponding cover will open and 

https://www.farming-simulator.com/mod.php?mod_id=138641

**Comment by Nad42** [comment]
I am experiencing same issue with 1.1.1.6. I have a single fill point for both seed & Fert, using the amazone Ceres Master 3570 (vanilla); It rolls up, opens the fert lid then proceeds to not fill any seed (the fert is already full).

**Comment by Nad42** [comment]
Now I very much don't have a clue what i'm doing here but... I have been looking at the code; seems to me main issue is that the "Load at destination" doesn't actually deal with a fill type at all... and line #388 in TrailerUtil.lua does not account for a trailer having 2 different covers... 
This whole task seems like it is written wrong to me; it should be utilising the function ADTrailerModule:tryLoadingAtTrigger(trailer, trigger, fillUnitIndex) instead of function AutoDrive.startFillFillableTrailer(vehicle)... i can try re-write it but its gonna take me ages cos I'm coming at this cold having to reverse engineer every variable to figure out where its coming from... I have no idea, for example, how to get the data from the selected fill type in the HUD and also I dont know what the trigger would be.... and what's the difference between fill type and fill unit?
