### ISSUE TITLE
Editor Misalignment [Question]

### ISSUE THREAD

**Issue by power1jj** [Stephan-S/FS19_AutoDrive#2111]
I've updated to the new version of the editor/application and my tracks and map don't align. This does not appear to be a 1x, 4x, 16 issue, as they are all off by a considerable amount.. It seems like the routes are anchored in the wrong place. First piture is on 1x and second is on 16x.
![snip1](https://user-images.githubusercontent.com/59424575/137773965-6c18c087-ab20-4fba-b2c7-ffb99155ba18.jpg)
![snip2](https://user-images.githubusercontent.com/59424575/137773985-0f50f30a-a27c-4c23-9e7f-1ddfb0493d85.PNG)

**Comment by power1jj** [comment]
Map is Midwest Horizons, its a huge map, probably 2048 x 2048, but I'm not sure. If I knew how to check I would, but all I could find was that it was 4x.
[AutoDrive_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/7449982/AutoDrive_config.zip)
e.

**Comment by KillBait** [comment]
Thanks for that.. i'll take a look at what's going on.

**Comment by KillBait** [comment]
> Map is Midwest Horizons, its a huge map, probably 2048 x 2048, but I'm not sure. If I knew how to check I would, but all I could find was that it was 4x.

It is a 4x map, does this look correct?

![](https://user-images.githubusercontent.com/7914589/139607793-ae2a89fc-ffc0-4890-8e76-fc5a9e4b3541.png)

I think the issue was the map preview size not being the correct size.. try the preview file i used here, give that a go and see if that fixes it.. [Midwest_Horizon MapImage.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/7450131/Midwest_Horizon.MapImage.zip)

**Comment by power1jj** [comment]
That fixed mine, thank you for your help and your time!
