### ISSUE TITLE
[BUG] All routes, waypoints deleted and mod reset

### ISSUE THREAD

**Issue by pummse** [Stephan-S/FS19_AutoDrive#2143]
AutoDrive Version: 2.0.0.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): 1
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich habe einen Kurs erstellt von meinem Heu Lager zum Viehmarkt um heu zu verkaufen und ihn gestartet. Hat funktioniert und nach dem abladen auf dem Rückweg sind alle Wegpunkte verschwunden und fps sind auf 16 gedropt. Ich habe dann gespeichert und mein Game neu gestartet. Jetzt ist der Mod komplett zurückgesetzt und alle Routen sind weg.
Kann ich die Wege irgendwie wiederherstellen? Oder was gibt es um das zu vermeiden?
Wäre nett wenn du mir da helfen könntest.
Mfg pummse

edit: Merke jetzt erst ich hab das in LS19 gepostet sollte eigentlich für LS22.

**Comment by Roby1164** [comment]
This is not a problem of AD, but of other mods. There are mods, such as player speed, autoload, and others, which come out of the normal functioning of the game, which give and have always given such problems. To restore everything, you must first check the lfile do log, then restore the save to the previous time, and delete any mods that may have created the problem, checking the log file. PS; with these reports, always attach the log file, without that, difficult to understand where the problem is.

**Comment by Iwan1803** [comment]
You should update to 2.0.0.2 and if the problem still exists then post your issue on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
