### ISSUE TITLE
Won't drive with pallet on front loader

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#233]
Tractor with front loader and pallet forks
When a pallet is on the forks, the tractor won't drive under AD. Perhaps this is because FS treats pallets as vehicles?
If the pallets are on a trailer then everything is fine.

**Comment by Stephan-S** [comment]
The pallet triggers the traffic collision warning yes, which is why AD won't start with it.
Since a pallet is not 'registered' as connected to the vehicle, I don't really see an easy way of ignoring them.
And I don't want to set it so that all pallets are ignored.
So, sorry, but probably won't be fixed :(
