### ISSUE TITLE
offset pipe

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#270]
I dont know whats up but everytime my combine needs unloading, the tractor and trailer goes to unload, but its never at right place under pipe either too close or too far away how can I tell what offset to have to make it closer to unload pipe

**Comment by HawkPat** [comment]
Did you try different settings at top left in AD menu?

![ad_menu](https://user-images.githubusercontent.com/52010642/60682052-0488d180-9e92-11e9-9dcf-896be497dd28.jpg)

**Comment by Opa-Andre** [comment]
Yes, this can be set in the AD menu - this is a global setting, so you'll have to change this  depending on the vehicles you're using. The bigger the value, the more you're away from the combines pipe. For example: When I use the big T9 combine, it's working best when using 0.0 m or max. 0.25 m, while when using the Ropa Panther 2, it's best when using 1.0 m because otherwise you'll be to close and a big (high) trailer will collide / crash into it.

**Comment by ploughedfieldman123** [comment]
I had been using that. but now realise I was increasing the right arrow, as I thought it made trailer closer but obviously it made it further away from pipe. I will now try left arrow  thanks all for help
