### ISSUE TITLE
Won't unload towed harvester

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#279]
Combine unload mode - when you have a harvester that is an implement towed by a tractor, AD does not get the message that the harvester needs unloading. The tractor/trailer never moves from the start point.

This is consistent with the Grimme and Ropa towed potato harvesters.

It seems like AD only works properly with drivable/self propelled harvesters.. ??

**Comment by Opa-Andre** [comment]
Does it work when you call the waiting driver manually ? Make sure the pipe is unfolded and you're in the "harvester", then press your defined key combination for calling the driver and he should start in a few seconds (might take up to a minute depending on the scenario)...

**Comment by aviator64** [comment]
Thanks for your suggestion. Unfortunately that does not work either, even with "Find Driver" enabled. I have also tried it with the harvester running under both Courseplay and in-game helper, as well as manually. No difference.

It looks like only self-propelled harvesters are going to work with AD's combine unload mode.

**Comment by Gariot** [comment]
Yes, only self propelled harvesters work in combine unload mode. Its kinda sad but hey, the towed harvesters suck anyway :D

**Comment by Opa-Andre** [comment]
Ok, in that case I would use AD in load / unload mode (load at the field). The harvester is controlled by CP as well as a tractor with an overload trailer. Because the CP overload mode (Mode3) isn't ready yet, I would use the combi mode (mode 2) for it. In the overload course you'll then need to include a parking point where your AD drivers are waiting. In order for this to work you'll have to make suer that the overloaders pipe is always unfolded and that the last waypoints in the AD network near the field as well as the overloader course are more or less straight in order that you are not running into collision issues (so that the vehicles are blocking each other)

**Comment by fudoido** [comment]
if i recall, i made that suggestion on CP github some time ago, that "workaround" for the lack of mode 3 :P

**Comment by Stephan-S** [comment]
Since this is such a small use case scenario, I hope you don't mind If I don't implement this. :-) Closed for now. Please reopen if the need for that feature is significant :D
