### ISSUE TITLE
Combine Unload mode - pathfinding bug

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#293]
Please see the attached screen shot. The tractor on the right is actually heading toward the far harvester, but it has got stuck behind the near harvester. This has happened numerous times.

Ideally, when approaching a harvester the tractor should follow in that harvester's path until the last moment and then turn outward to line up with the pipe. That would prevent these conflicts when multiple harvesters are in a convoy.

Hope that made sense!

![fsScreen_2019_07_20_12_43_44](https://user-images.githubusercontent.com/19857526/61579390-45bcea80-aafc-11e9-94c3-6f9a04db1911.png)

**Comment by fudoido** [comment]
never happened to me. are you sure you dont have a courseplay course activated at same time as autodrive cours? that might conflict.
i sometimes get trailers or tractors stuck in the discharge pipe, but never it happened for them to go the opposite side of the combine. :/

**Comment by Stephan-S** [comment]
hey @aviator64 Since the pathfinding has gone through some iterations, I hope this issue is at least reduced. As long as fruit detection is turned on, the driver should try to find a way that avoids fruit and thereby also the other combines (mostly). I don't wanna block all grid cells that contain vehicles, since they are hopefully moving and out of the way by the time the driver arrives there.
Only the assigned combine is blocking it's grid cells to avoid a collision with this stopped combine.
