### ISSUE TITLE
Considering steering angle when choosing the best route

### ISSUE THREAD

**Issue by cristiancundari** [Stephan-S/FS19_AutoDrive#34]
Hi, sometime the choosed path is not correct, and the tractor gets stucked on objects because it tries to make a 90+ degree turn. I drew an example route where the blue one is obviusly a two-way path and the green one is only one-way. I want the AutoDrive to avoid the path which requires you to steer more then 90 degree (or even less), so it can choose the best route to drive on.

![AutoDrive](https://user-images.githubusercontent.com/37112275/55718021-fe9e6400-59fa-11e9-9d17-556c3756d8b1.jpg)

**Comment by Stephan-S** [comment]
The problem is that during the computation of the fastest paths, there is no concept of angle between the lines. As long as there is a connection, it will be used. I suggest using double sided roads with caution and only where really needed. You could also make sure that there is alway a better location available to turn the tractor around, which I assume is usually happening in this scenario.

I will think about adding this to the calculation step, but this is a huge overload and I will see if I get to it.
