### ISSUE TITLE
Reversing

### ISSUE THREAD

**Issue by Squibbb** [Stephan-S/FS19_AutoDrive#340]
Hi Steven,
Could you possibly make a reversing option while creating a course. Just A Thought

**Comment by alpha117** [comment]
+1

**Comment by RUGhost** [comment]
It would be awesome. I hope may be one day we see this feature in AD

**Comment by FforFarm** [comment]
It will be awesome in multiple situations. 

When reversiong into a silo
Reversing into a parking spot (Not all halls is drive through)
And even more awesome would be reversing in a garage, detatch and park the implement, and drive on ;)

**Comment by Stephan-S** [comment]
I am not completely against including reverse driving but I feel it could cause a lot more problems than good. Because if I include it, it won't properly reverse the trailer/equipment but will just try to align the tractor with the road. So you won't be able to use it like the rest of the network.
That's why I am still hesitating to actually include this option.
