### ISSUE TITLE
Problems due to different names of cards in multilingual versions of the game.

### ISSUE THREAD

**Issue by Pirate-Rat** [Stephan-S/FS19_AutoDrive#347]
AutoDrive_Felsbrunn_init_config.xml is not initialized. AutoDrive_Фельсбрунн_config.xml is created. <Felsbrunn> - <Фельсбрунн>
(Sorry for my bad english. Machine translate.)

**Comment by Stephan-S** [comment]
Thanks for telling me that. I wasn't aware of that.
The file format will stay this way for FS19, but I will get rid of the map name for the FS21 version, so that this shouldn't be an issue than and also upgrading modmaps doesn't break your AD courses.
I will close this here on the FS19 version. Sorry for that, but thank you for telling me about it!
