### ISSUE TITLE
New GUI for settings

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#388]
@Stephan-S dont you want add new tab (eg HELP/FAQ) to GUI when we have this option now and add there some useful info about using AD. I think many ppl left AD cuz some important functions are hidden for them.

Some examples..
- needed set right filltype by clicking to filltype area
- editing name of waypoints by mid/right click to "Waypoint icon" button
- deleting waypoint name by mid/right clcik to "Delete node" button
- how to set unloader for combine in right way..(there is needed also set combine)
- cooperation with CP for autorefill 
- blue course works as 2 ways route
etc

Sure you now better by opened issues what is problematic for users... Also translators will be happy make translations for that I assume

**Comment by Stephan-S** [comment]
I would love to add some info to either the ingame help menu or as you proposed, the settings GUI.
But this will definitely require a lot of new translations :(
And of course also a lot of good tutorial images that go along with the text.

I will try to do something about that!

**Comment by raxtor** [comment]
If you want change AD HUD, should be better wait for that... just add other important points, like today new 20m distance between seeds and fert... No need any big image tutorials if new HUD will be added imho.

**Comment by raxtor** [comment]
what about new AD logo? Feel free to use it if you like it.
![ad_logo](https://user-images.githubusercontent.com/831266/63824765-91af4a80-c958-11e9-8874-e98f5781ef8b.jpg)
[AD_logo.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3549036/AD_logo.zip)

?

**Comment by raxtor** [comment]
Bit different version..
![ad_logo1](https://user-images.githubusercontent.com/831266/63834433-98988600-c975-11e9-8ae4-740c6a28e2b4.jpg)

**Comment by raxtor** [comment]
But most of them I would like rename it to AI DRIVER :-)

**Comment by Stephan-S** [comment]
@raxtor I like your enthusiasm. But the logo and the name is set in stone :-)
Oh, and almost ready to publish a few updates to the new mode, if you want to test it again

**Comment by raxtor** [comment]
Sure.. have some free time yet..

**Comment by Stephan-S** [comment]
If you have some free time and want to put your designs into AutoDrive, you could start with some of the new logos for the new HUD. 
For example the speedmeter you designed in button form. Or any other buttons you might think could use a redesign.
If you provide them to me in 128x128 as png or dds file, I will either just replace them in the current HUD if I like them or integrate them in the redesign.

Btw: Updated the source files. So feel free to check the new mode out again :-)

**Comment by raxtor** [comment]
can you check *.dds in attachment if it is in correct format for FS?
[AD_logo.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3549673/AD_logo.zip)

**Comment by Stephan-S** [comment]
It should be DXT3, at least this is what I'm always using.
I use paint.net to save my png as dds files.
Don't have any tool on hand that shows my your compression setting (DXT mode), sorry

**Comment by raxtor** [comment]
I prepared some new icons for AD modes and some other buttons... will continue if you will find it as good.. there is new state icon for Parking... (green LED signalized set parking place)
Check it out and let me know... (some game screenshot would be nice)
![park_set](https://user-images.githubusercontent.com/831266/63875822-901b6c00-c9c4-11e9-8e1f-3e1f0ef151a7.png)
![pickupAndDeliver](https://user-images.githubusercontent.com/831266/63875823-90b40280-c9c4-11e9-890e-0ec10b2dc768.png)
![silo_load](https://user-images.githubusercontent.com/831266/63875824-90b40280-c9c4-11e9-8252-956c396173f8.png)



[textures.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3551944/textures.zip)

**Comment by raxtor** [comment]
Well.. I made test and.. icons are much smaller than 128x128px for 100% HUD :-) I have to rework it...

**Comment by raxtor** [comment]
1.0.5.2 - NICE HUD!!! :-) Time to finish icons.
Just a question.. 100% HUD has 32x32px icon.. why are you using 128x128px as default... shoudnt be enough 64x64px? I assume better result for 64x64 for decreasing size to 32x32px.

**Comment by raxtor** [comment]
@Stephan-S here is first part of Icons for new HUD... seems I founded trick for good look in small size..
[textures.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3585161/textures.zip)

![button_base_BGA](https://user-images.githubusercontent.com/831266/64450938-67d9ee80-d0e3-11e9-9d1a-5da2a28695d2.png)
![button_base_combine](https://user-images.githubusercontent.com/831266/64450939-67d9ee80-d0e3-11e9-965a-407b55e18c79.png)
![button_base_pickup_deliver](https://user-images.githubusercontent.com/831266/64450940-67d9ee80-d0e3-11e9-81ea-d5c02e3596ef.png)

**Comment by raxtor** [comment]
Hello @Stephan-S,
I think its done...
**100%**
![HUD_100](https://user-images.githubusercontent.com/831266/64464796-8ce15800-d109-11e9-913a-46386fc67dac.png)

**75%**
![HUD_75](https://user-images.githubusercontent.com/831266/64464804-98cd1a00-d109-11e9-825f-d50e8cfd760e.png)

New Icons for HUD without function yet:
**FillLevel** - for individual settings for every vehicle
![fillLevel](https://user-images.githubusercontent.com/831266/64464871-f7929380-d109-11e9-9d47-df344a54d727.png)

**Parking** place Set - second state when parking place is set
![input_parkVehicle_2](https://user-images.githubusercontent.com/831266/64464900-1ee96080-d10a-11e9-9ea7-1a22009d2e02.png)

Also HUD **shoud change overlay icon by mode** (yellow circle).. u can use icons from buttons Load/Unload. Now its only done Pickup and Deliver as master...
![HUD_100_info](https://user-images.githubusercontent.com/831266/64465019-bb136780-d10a-11e9-9667-be5e57b4b8c8.png)

Thats all... I added also **new logo** (store.dds) :-)
[FS19_AutoDrive_newButtons_Logo.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3585947/FS19_AutoDrive_newButtons_Logo.zip)

**Comment by Stephan-S** [comment]
Hey @raxtor nice work. I really like some of those new icons.
But, and please take this as very personal and biased opinion from me and not as generals critique of your work and design :-) 
1.) I would prefer a more minimalistic approach.
What I mean with that is, only colors for currently active objects/buttons - this is quite important for me!
2.) I think that the new mode icons with the truck, combine and wheelloader just look a bit too 'toylike' and a bit like taken from Playmobil if you know what I mean. And I would prefer something that tries more to resemble the real life object rather than an oversimplified piktogram.
For example I would replace the truck with a trailer that I have used but maybe a closed one with arrows pointing in and out to replace the green and red block

3.) I am not sure that your icons for 'show neighbor, toggle connected etc.' are more intuitive than the ones already in the mod. You might be on an interesting path there, but once again, I would like to reduce the colors as much as possible. Although they are more acceptable in the icons that only display when you activate the 'edit mode'.

Would you mind making some toned done versions of your icons? So with less colours? For example I like the idea of the two icons for the parking button, but I wouldn't want it to be blue all the time. The greyed out version is fine, but the active one should not be so 'in your face' if you know what I mean :-)

So again, thank you very much and please please don't take it as criticism of your work. This is just my personal opinion on the matter :-) And my taste might be different from yours or the geneneral consens :-)

@CairoAmun Hey, hast du eine Meinung zu den Icons von raxtor? Mir sind sie teilweise etwas zu bunt und zu knallig und gerade die Modus-Icons etwas zu 'Playmobil' artig. Ich bevorzuge hier ein etwas dezenteres Erscheinungsbild aber bin generell offen für Icons die vielleicht besser rüberbringen was die Buttons für eine Funktion haben oder generell besser aussehen als meine alten :-)

**Comment by Stephan-S** [comment]
@raxtor I think your loop counter is really looking great. Can you make two versions of the icons? One with green numbers and one with white? The green one will be used when autodrive is active in 'pickup and deliver' mode and is counting them down. And in all other cases I would like them to be white.
But the loop icons is just so much better :-)

Also the record button. Can you make the default one again white/greyed out? I like the active one with the arrows underneath and would immidiately use them, but I don't want the default red icon

**Comment by raxtor** [comment]
White loop numbers, grey Record button, grey Loop button..
[textures_fix.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3586447/textures_fix.zip)

**Comment by raxtor** [comment]
ad 1) I can make grey state for many of them, but many buttons havent hover effect.. do you plan add it?
ad 2) @Stephan-S we have 32x32 space... I would like use more light stylem but than would be hard find what that stain is showing like  harvester Icon shown in actual version. Also pls consider, many ppl are using 75% HUD, cuz default 100% FS GUI is simply too big... So I choosed icons whose are working also in 75% HUD... we can use cutter for Combine and shovel for BGA, not whole vehicle.. I have done such version too...
ad 3) isnt too big problem change green to white or grey... as I sad, only 1 editing button have 2 states.. are u plan ad hover effect?

Anyway feel free use or rework icons... If u can use Photoshop, I will send you *.psd.

In account to colors.. yes, I can make more grey look... but personally I like more when my car dashboard uses lights :-)

btw more logic HUD by me...
![HUD_new](https://user-images.githubusercontent.com/831266/64473163-2c343880-d166-11e9-9902-abddd2a66313.png)

**Comment by CairoAmun** [comment]
Hi,
der Hud sieht nicht schlecht aus. Die Farben sind allerdings ziemlich knallig. Das Rot sticht besonders hervor. Ich versuche mir gerade vorzustellen, wie es aussehen würde, wenn man das Rot gegen das Grau tauschen würde, so wie es im Parkschild als Hintergrund ist und das Grün vielleicht dunkler.
Ist schwierig, weil es ja auch Geschmackssache ist. Ich denke aber mit etwas dezenteren Farben sieht das bestimmt noch besser aus. Die Icons an sich seht sehr gut aus.

Viele Grüße Cairo

**Comment by raxtor** [comment]
@Stephan-S maybe you can create voting thread with new and actual HUD... than will be more cleare what user are prefering.. ofc after we will make some finetuning here...

**Comment by Stephan-S** [comment]
@raxtor Do you still have the images? I'm currently working on the HUD with a good friend of mine who is helping me out with the design.
I would like to keep using your symbols but they all contain the background with the fixed color instead of a transparent background.
So if you still have your source files and could provide them without background, this would help us out :-)

**Comment by raxtor** [comment]
@Stephan-S Yes, still stored somewhere.. is layered PSD ok for you or do you prefer every transparent icon in single file?
Anyway I found free icon database in style you like. Maybe you will find there something good for you. https://app.streamlineicons.com/streamline-light
I was thinking about new HUD... many ppl are crying, they dont like new format. Maybe if u will add 1 column than it will be more acceptable for them. I propose change road sign icon to record icon. In fact that hidden line is all about course recording/editing and in addition you will able use 2-3* buttons for recording (1 way/bi-direction/bi-direction offseted*).
