### ISSUE TITLE
Translation optional

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#40]
Hi Balu, I would like to know why you didn't want to add the translated file I've push few times ago please? Don't you need French now ?
Regard

**Comment by Stephan-S** [comment]
Hey, sorry. I was quite busy.
I had to remove it before it could be certified at the Modhub because some translation where missing at release date and the description was different from the original (that I added after yours).
So if you could push a full translation of the current version (1.0.0.6) I will definetely include it.
But the problem as described above is, that I can not include incomplete translations in an update to the Modhub :( So every time I add something to the Moddesc.xml (which happened with every update lately), I have to wait for you guys to update the translation as well. So I was waiting for the right time to merge your push request.
Sorry for that!
And thank you for your participation and help!

**Comment by Anonymous-any** [comment]
I was afraid :) thank
