### ISSUE TITLE
Mod Hub update

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#54]
You can't put the update on ModHub, today 1.0.0.0 is still present ...

**Comment by Stephan-S** [comment]
Sorry, I don't know what you are trying to tell me. What exactly is your point here.

**Comment by Roby1164** [comment]
Here:
https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=127335&title=fs2019
This is your mod, present on the ModHub of the game, but today it is stopped at the first version, the 1.0.0.0 ......

**Comment by Merlin110480** [comment]
Ich denke er fragt warum im Modhub noch 1.0.0.0 ist und es kein Update gibt.

**Comment by ploughedfieldman123** [comment]
because the latest releases are here on Github

**Comment by Roby1164** [comment]
> because the latest releases are here on Github

That the latest versions are here is well known, but, since it is present on ModHub, it would be nice to have it updated there too, which is easier for everyone, have it updated, especially when playing on a Dedi Server ......

**Comment by Roby1164** [comment]
> because the latest releases are here on Github

And to tell you another, you know how many are not able to download from Github ????? Many more than you believe.

**Comment by Anonymous-any** [comment]
Ok hi hey Roby I think we understand what you say but you must know too it is not conceivable modhub host buggy version don't you think ? Authors have already hardness to deal with modhub because some thing we don't know are modhub restricted 2nd Arg too because their babe need to be as better before players say blahbla that not run log errors, this is that buggy that.... is it ok  where my bad english want to show you think to go ? I think too you know about coding is not easy and errors can happen more faster than you believe ok ? think to them if it was you...
Ps: Think to that too you have luck here where this Author allow and give faster fixes and versions here on GitHub to give pre-mod to players tester while this is not the case for many of them nowadays, if you want my opinion, do not make him waste his time with your modhub worry, take your version and thank him do not you find better ? 
To reply you your pleasure words reflection:
`And to tell you another, you know how many are not able to download from Github ????? Many more than you believe`. then they are child's ? stay calm

My Br

**Comment by Stephan-S** [comment]
Hey Roby,
Anonymous-any sums it up quite well. I can release a new version much faster here on Github and receive feedback from you guys. If I am happy with a version I will submit it again to the Modhub. But since the testing cycle there takes around 11 days now. The then released version will already be outdated by at least 2 or 3 versions at the current rate.
So of course it would be more convenient for all users to have the most up-to-date version on Modhub. But that is simply not possible.
Once the combine unloader function seems to work fine and the new settings menu includes the options I would like it to have, I will update the Modhub version.

**Comment by Blacksnake51** [comment]
Hi Stephan, I have to dig up the topic again. I now had the case as a new Autodrive user that I had loaded the current version of GitHub. But FS19 updated to the old version v1.0.9.1 from the ModHub (https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=127335&title=fs2019). As a result, FS19 no longer loads a game with AD 1.0.9.1.

Can you delete the old mod in the Modhub that he doesn't always want to update ingame? Thank you
