### ISSUE TITLE
Rail crossing detection

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#582]
![fsScreen_2019_10_05_14_34_39](https://user-images.githubusercontent.com/831266/66262410-5a497e80-e7df-11e9-9c52-f8050edfca86.png)
Not sure, if there is some kind of rail crossing detection, but I have same issue also with default map... its not major problem, because vehicle is stopped physically. Just for future....

**Comment by Voidheartd** [comment]
Would like to see a fix for this if possible. Have to make the train stay out of the way if I don't want vehicles to get stuck.

**Comment by Stephan-S** [comment]
Is someone able to tell me the collision bit of the railroad crossings?
This would save me a lot of time. Thank you!

**Comment by raxtor** [comment]
What are you asking exactlly?

**Comment by Voidheartd** [comment]
Could you ask one of the courseplay devs? I know CP stops for the trains so they should know. Or maybe you could find it in the CP code?

I had a quick look and the most relevant thing I could find was this function:

https://github.com/Courseplay/courseplay/blob/master/TrafficCollision.lua#L242

**Comment by Stephan-S** [comment]
Should work with the current source files :-) At least with all vehicles I tested it with.

**Comment by raxtor** [comment]
Great! GJ

**Comment by raxtor** [comment]
last github version... 8.11.19 22:05
![fsScreen_2019_11_08_22_04_05](https://user-images.githubusercontent.com/831266/68510500-0285b380-0274-11ea-9fdc-d61c39dc4f71.png)

**Comment by raxtor** [comment]
Maybe weight in front?

**Comment by raxtor** [comment]
@Stephan-S  
![fsScreen_2019_11_08_22_23_11](https://user-images.githubusercontent.com/831266/68511869-2991b480-0277-11ea-83ca-d5e707be499b.png)
![fsScreen_2019_11_08_22_26_35](https://user-images.githubusercontent.com/831266/68511871-2991b480-0277-11ea-8fcf-2e392966cd45.png)
After shot investigation I assume there is problem if CP is active and seeder is on reffiling course... and weight can be also problem imho

**Comment by MicaelJarniac** [comment]
I've installed AutoDrive a few days ago (1.1.0.4) and never had any luck with rail crossings.

I mean, it's not much of a problem most of the time. Usually AD just drives straight into the barriers, then keeps on trying to push them, until they open and it can go through.

But sometimes things don't work quite well. It sometimes gets thrown out of its way by the barrier opening, for example.

I tried searching for a similar issue here, and found this closed issue. It's meant to be fixed, but it's not working for me.

Instead of opening another issue, I decided to first comment in here.
