### ISSUE TITLE
Pallets on trailer trigger collision detection

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#621]
The trucks from this mod pack wont drive at all if i have loaded Egg Pallets.
If its empty or loaded with square/round bales, it drives perfect.
https://ls-modcompany.com/filebase/file/518-friesenjung-transport-pack/#overview

**Comment by Woife1** [comment]
It is known.
Autoload didn't work with AD
Use CP if AD did not work with the Autoload Vehicles

**Comment by geo-luchs** [comment]
Hi Woife1
but it's not in general not working with Autoload.
It seems only to be with egg pallets

**Comment by SledgeHammer75** [comment]
for me, at least paper and empty pallets are also effected

**Comment by bojanh66** [comment]
And seed/fertilizer pallets from shop too.
It seems all pallets are effected.

**Comment by geo-luchs** [comment]
I've tested it now in a different way with pallets on NF Marsch map.
the trailer is an autoload , but I didn't used the autoload function. I took only one pallet and put it on the trailer.
AD drives.
I took a second pallet and put it on the trailer at the end.
AD drives.
I moved both pallets directly at the front of the trailer directly over the end of the truck.
AD didn't drive anymore.

no autoload function used.

**Comment by jcmbennett** [comment]
When i ran into this issue with AD and my autoload flatbed full of pallet I noticed it happens when the turning angle is too tight and the crates hit the cab making it impossible to continue the turn. So i tried a truck where the hitch is really far from the cab. I used this mod Western Star 4900SB/XD v1.1.0.0 FS 19, the dry cab model and it works perfect! Even with really tight angles the cab never comes near the trailer and thus never collides with the crates.

**Comment by geo-luchs** [comment]
@Stephan-S can you Control the checking Box for Collision?
Or is this defined in the vehicle mod itself?
Because:
Trucks are Not driving if Therese is any collision detected around it all. Also behind the truck. Or better over the truck.
If i'm disconnecting the trailer, the trailer is still over the end of the truck , and AD will not drive.
If empty trailer is connected , AD is driving.

Now the Text step:
If round bales are loaded, AD will drive,  too.

But vorher Elements like pallets are Different.

What Could be different?

A) pallets could have a different collision Definition
B) The trailer, when items are loaded is working different with round bales and pallets.. could it be that loaded round bales will be one unit together with trailer and connected truck?  And pallets will Not be one unit with trailer? Therefor pallets are detected as different items with Down collision Box?

Only brain storming, sorry.  I've infortunately until now no knowledge with giants Editor  and how items are defined with collisions

**Comment by geo-luchs** [comment]
I've found the difference, why round bales are working, and everything else not.

Roundbales are Items, which are written in items.xml
All others, like pioneer pallets, eggbox , ... are written in vehicles.xml

Then it's clear, that the collision check is not working for roundbales, but for all others, isn't it?

Question is: how is collision check working? Because it's only a small area in front of the loading plane.

With trailer: if you are loading after the truck, AD drives.
With a truck from Friesenjung mod:
Load after 2nd axis, it works, too.
![Pallett_on_truck_with_AD](https://user-images.githubusercontent.com/53658780/67940337-b2538500-fbd3-11e9-89c2-3fcb3b938134.PNG)

**Comment by Woife1** [comment]
just for example the beerbarrelpallet(Bierfasspalette) from the NF-Marsch has the collision bits 3, 12, 13, 23 and 24

**Comment by geo-luchs** [comment]
@Woife1 I did already a test, and modified the collision Mask of eggbox, and also the other way  for round bales.

If doesn't Help. So this collision critera can't be the own criteria. 
I believe round bales are working because they are items Not vehicle.

**Comment by geo-luchs** [comment]
I can try it today evening.
Yesterday I Asked already Fedaction if pallets have to be defined as vehicle.  He said: yes.

Maybe because of the unloading process in triggern.
Round bales in a trigger will be removed in one Step.

So this is no Option to Change pallets.

I hope  Stephan has an anwser  how HE can influence the collision check. Hopefully HE can change it only to the front

**Comment by geo-luchs** [comment]
Hey @Stephan-S  : Great. it works. now AD can drive with eggboxes, pallets.
Others I've not tested yet, but I'm sure, they will work , too.

Great job :-)
Thanks a lot. This is now really improving the daily work on the NF Marsch ;-)

**Comment by Woife1** [comment]
great to hear this 
Stephan is doing a great job :heart:
