### ISSUE TITLE
Is there a easier way to edit an existing route?

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#667]
Currently, the only way I've known to edit existing routes is by using a vehicle and driving with it around the routes, using the red line as a guide to create or delete waypoints.
Is there any faster way, for example, using the mouse directly on a map?

**Comment by raxtor** [comment]
No, but you can use AD editor.. you need Java support in your PC for that. If you want download course editor, [download whole repository of AD](https://github.com/Stephan-S/FS19_AutoDrive/archive/master.zip) as *.zip and than extract AutoDrive_Course_Editor

**Comment by rogeriodec** [comment]
Hmm, that's interesting. 
However, I don't see how can I interact with the routes using the mouse (left, right, middle click, select, etc). 
Any documentation?

**Comment by raxtor** [comment]
Dont think so.. try experimenting or [read closed issues](https://github.com/Stephan-S/FS19_AutoDrive/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+editor) for better understanding...

**Comment by rogeriodec** [comment]
That's sad, when an app is released, even in dev mode, at least some basic guidance could be given.
I researched but didn't find anything that explains the basics of how to edit routes with the mouse (as I said, apparently no mouse action is working).
Could you help with any notion?

**Comment by raxtor** [comment]
Hey man, its OneMan show and @Stephan-S is **pretty busy** boy! 
I am not familiar with AD Editor but I am sure somebody will help you later.. Its sunday night... you have to wait a bit. I assume you can click to any course piont and than you can edit him as you want. Del/move etc.

**Comment by newbie-near-cologne** [comment]
I tried it and it works fine. You select what you want to do, for example "Move Nodes", then you can click on a node and move it. Same for "Delete Nodes" and so on. First choose by left mouseclick what you wanna do and as next the node(s) which you want to modify. With mouse wheel you can zoom in and out. With left you can move the map in the window.

**Comment by newbie-near-cologne** [comment]
First step is you must load the Autodrive config which you wanna modify. As next you must load the map in png format. So load the *.dds file in an editor like paint.net and save it as *.png. Then I resize the window. The map doesn't fit but when you use the mouse wheel it's automatically change the size in fit in your selected window size. Hope it help you.

**Comment by rogeriodec** [comment]
Thank you, now I'm learning how to use it. Although not so user-friendly, it's still a lot easier than to create routes be driving a vehicle inside the game.
Now I'd like to know: is it possible to load the editions made on AD Editor without leaving and reopening FS19?

**Comment by Spielbauer** [comment]
Hallo, will mich mal hier dranhängen. Hab den Editor runtergeladen und entpackt, finde aber keine java.exe zum starten. Was mache ich falsch? Falls das hier einer liest der sich mit einem PC auskennt :-) wäre ein Tipp super.
![Autodriveeditor](https://user-images.githubusercontent.com/54139649/67204826-a8c96080-f40e-11e9-9fde-e69e68a21843.PNG)

**Comment by rogeriodec** [comment]
@Spielbauer https://www.java.com/en/download/

**Comment by worker2419** [comment]
> Thank you, now I'm learning how to use it. Although not so user-friendly, it's still a lot easier than to create routes be driving a vehicle inside the game.
> Now I'd like to know: is it possible to load the editions made on AD Editor without leaving and reopening FS19?

yes, i will try to explain
first activate AD HUD and switch to editor mod
press left Strg and left Alt and Keypad 2
AD will create 2 folders in
My Games\FarmingSimulator2019\FS19_AutoDrive_Export
My Games\FarmingSimulator2019\FS19_AutoDrive_Import
Messages in the console or in the log are shown
AD: creating xml file My Games/FarmingSimulator2019/FS19_AutoDrive_Export/AutoDrive_mapname_config.xml
AD: Finished exporting routes
leave the game without closing
open autodrive editor and load config from export folder
configure map and save new config file to import folder
go back in game
press left Strg and left Alt and Keypad 1
Messages in the console or in the log are shown
AD: Trying to load xml file from My Games/FarmingSimulator2019/FS19_AutoDrive_Import/AutoDrive_mapname_config.xml
AD: Loading xml file from
AD: Loaded Waypoints: number of waypoints
close editor modus and then AD HUD
reopen HUD, otherwise new targets are not visible

@Stephan-S  new routes work, but are not displayed correctly (see screenshot), all other changes work
![AD_01](https://user-images.githubusercontent.com/47278102/67239037-92db9000-f44e-11e9-81f0-08f715c0c2d3.png)

**Comment by rogeriodec** [comment]
@worker2419 thanks, but this way is absurdly easier just to close and reopen FS19...

**Comment by Iwan1803** [comment]
There are hardly any videos who explain the editor, but the others explain what to watch out for when recording.
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/613
