### ISSUE TITLE
AutoDrive XML is not being saved

### ISSUE THREAD

**Issue by Kokolores11** [Stephan-S/FS19_AutoDrive#685]
I tried to rename a mapmarker in game by adding a new one on the same waypoint, hoping that it would overwrite the old one.
This led to two markers on the same waypoint.
When I deleted the waypoint only one marker disappeared. The second one was still there.
I saved the game and tried to edit the XML file and remove the marker without waypoint.
However there was no AutoDriveXML in that savegame.

I would suggest, that you could edit a marker if a marker for this waypoint already exists.
Ideally you would already have the old name in the popup to edit.

I can't think of any reason to have two markers on the same waypoint. But if I'm missing something, deleting the waypoint should delete all markers for that waypoint.

But most importantly the XML should be saved even if there are errors, so that you have a chance to edit it by hand.

Thank you for all your hard work!
Best regards
Kokolores

**Comment by Stephan-S** [comment]
You can simple use the secondary function of the 'Create Destination' button.
So either use right or middle mouse button on it and it will allow you to rename the currently selected target destination.

The xml file is not stored because it probably ran through some unexpected error that is probably written in the log. If you provide the log with the error message I'm happy to solve this problem. But the real problem here is that I allow users to create two destinations at one point which I should definitely catch.
So thanks for bringing that up.

You can always find your latest XML files in the Savegame backups folder which Giants luckily creates :-)
If you want a manual save, use the export config function, which will generate the xml file in the AutoDrive_Export folder.

Best regards,
Stephan

**Comment by Kokolores11** [comment]
Thank you for the quick answer.
Unfortunately I don't have the log file anymore.
Good to know that there is a secondary function :)

Best regards,
Kokolores
