### ISSUE TITLE
AD Editor spoiled AutoDrive_Ravenport_config.xml

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#686]
After using AD Editor to change routes a few times, I realized that apparently after a while the routes had disappeared.
But luckily, Giant-Software created the "SaveGameBackup" folders and I was able to recover an older version, which went back to work, although losing several modifications I had made.
VISUALLY comparing the corrupted version with the functional version of the **AutoDrive_Ravenport_config.xml** file using AD Editor itself, I realized that the routes were not lost, but rather, AD editor created a type of ZOOM on all routes, leaving them proportionally adjusted as if they belonged to a larger map.

AutoDrive_Ravenport_config.xml ok (recovered from the backup):
![image](https://user-images.githubusercontent.com/11199752/67391007-222e9380-f574-11e9-8dee-f6df2347dd7c.png)

Messy AutoDrive_Ravenport_config.xml:
![image](https://user-images.githubusercontent.com/11199752/67391102-4d18e780-f574-11e9-839f-edde61303e3b.png)

If you look closely, you will see that the routes are there, but applied to a larger scale, which obviously does not fit the current map.

I did a Diff online comparison (https://www.diffnow.com/compare-clips) and the result shows basically differences in waypoints coordinates:
![image](https://user-images.githubusercontent.com/11199752/67391406-fa8bfb00-f574-11e9-9184-895d93a4484f.png)

This is the HTML page of the comparison:
[__edp_output__3d792e8b-1a39-423c-b470-5225bc61e1ea.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3762273/__edp_output__3d792e8b-1a39-423c-b470-5225bc61e1ea.zip)

This is the working XML file:
[AutoDrive_Ravenport_configOK.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3762275/AutoDrive_Ravenport_configOK.zip)

This is the messy XML file:
[AutoDrive_Ravenport_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3762282/AutoDrive_Ravenport_config.zip)

**Comment by Stephan-S** [comment]
@rogeriodec You probably had for whatever reason clicked on the 4x button in the editor, which will cause this exact scaling which is used for 4x or 16x times maps.
And if you now complain about missing documentation of the editor: I don't f**ing care! I don't have the time to keep an up-to-date documentation on an ever evolving and changing piece of software which I am the sole maintainer of!

While I appreciate you pointing things out in the mod that could use improvement, I am honestly fed up by you not bothering to check even the smallest bits out for yourself. If you get stuck after having tried things for yourself and after checking every possible source of information (previous issues / youtube / reddit etc.) I am more than happy to help out. But please, please start thinking for yourself instead of running to this github repository for the simplest things! Thank you!

I and all users who actively try to help you here have better things to do with our time.

And just for your information: One of these better uses of my time is a thorough documentation that I am currently writing.

**Comment by rogeriodec** [comment]
@Stephan-S Probably I have clicked on these 4x and 16x buttons and precisely because I do not know what they do is that this question arose.
I am self-taught in many areas, especially IT, where I have worked for over 37 years, probably longer than you are old. Not that the time argument serves as a constraint, but because there is a great experience in this area and when I like something, I try to help the way I can, which in the case of this mod, help to indicate possible improvements.
But from the harshness of your words, I realized that, as you said yourself, you don't care about that.
No problem. Each person has a way of being.
Anyway, I appreciate your effort in making this mod available to everyone for free, which provides us with great fun and leisure.
