### ISSUE TITLE
Improvement: turning on all vehicle lights at night

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#714]
When night, it seems AD is not turning on ALL light of the vehicle:
![image](https://user-images.githubusercontent.com/11199752/67715186-15f96a80-f9a8-11e9-8bd9-4dfb95a9038c.png)

**Comment by rogeriodec** [comment]
@TyKonKet Why did you close this issue?

**Comment by TyKonKet** [comment]
@rogeriodec 
Lights are working well now, I've tested it few days ago when I improved how they works, now if a vehicle is not working correctly, is because it have a wrong lights setup.
Actually we are not really taking care of lights activation but we are forwarding this task to GIANTS AI, so I'm pretty sure it have no problems.

Obviously if a mod/vehicle is wrongly set, we can't do nothing, how can we understand what kind of lights we have to turn on?
