### ISSUE TITLE
Unload combine truck chooses bad turn angles for drive to start

### ISSUE THREAD

**Issue by Voidheartd** [Stephan-S/FS19_AutoDrive#715]
It seems a recent update has done something to the field pathfinding. After reaching the chosen unload level the truck keeps making impossible turn angles on the 2nd segment once it begins the "drive to start". The 1st segment is a doable angle, but the 2nd is always more than a 270-degree turn which the truck can't do. This 2nd segment is also very long which I don't remember seeing before.

In the attached image you can see that bad 2nd segment, the 1st segment (yellow line is an approximation of it) being a gentle turn from where the truck had unloaded the harvester and backed up (the red line).

The truck then does a loop attempting to reach the start of this 2nd bad segment. If it reaches it then it will finish the route. Otherwise, it gets stuck going in circles.

![image](https://user-images.githubusercontent.com/3398909/67740114-19621580-f9eb-11e9-931f-e904e5d9aa1d.png)

**Comment by Stephan-S** [comment]
So he is getting stuck in circles in the marked circle, right?
But the direction angles I draw in there are also correct?

Then this is an issue where he is looking far ahead to where he has to go and is making a steep turn but by doing this sharp turn he is cutting this corner and never 'triggers' that he reached this second waypoint, correct?

Or am I misunderstanding you?
This might be a problem that is rather vehicle related. Since I don't have this issue with tractors and thus never noticed it.

**Comment by Voidheartd** [comment]
It's weird because it does hit the start of that long segment, which would normally mean that it would then drive to the end of that segment and the beginning of the next. But it instead tries to hit the start of the segment again, causing the circling.

I would then think it's because it's hitting the segment at a bad angle so it isn't counting, but if it does get there during the circling that is also at a bad angle so that can't be the reason.

**Comment by wallsingham** [comment]
@Stephan-S 

The pathfinding begins whith a very narrow angle and starts right in front of the vehicle. So it is simply impossible for the vehicles to take the proper turn. They are constantly turning in a circle.
Perhaps it could be helpfull to insert a variable "turning angle" in the Vehicle settings. So that this value will be includet in the pathfinding algorithm.

![grafik](https://user-images.githubusercontent.com/56741972/68613638-7d8eda00-04bf-11ea-83ba-612f48208ccd.png)

**Comment by wallsingham** [comment]
The unloaders are doing quite well now. No too sharp angles are generated for the unloaders anymore. Thanks to @ Stephan for fixing this.

The (too) sharp start angles are also a problem during normal startup. The same applies if the unloader is full and moves from somewhere in the field to the start point. The vehicles select their travel segment regardless of the angle of their own position on the route. They then turn around in a circle until the fallback option occurs.
Suggestion: Perhaps to make it work the destination trip to the first route segment would have to be done with a suitable angle, which either depends on the turning circle of the respective vehicle or is generally so wide that all Fehrzeuge can drive it.

**Comment by wallsingham** [comment]
Possibly the same algorithm could be used for the destination trip to a route segment that e.g. is used for the destination trip to the harvester. This one comply whith the position angle of the harvester.
