### ISSUE TITLE
Improvement: can AD detect when harvester (with cp) has finished his route?

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#729]
Hi Stephan

In combination cp+AD  unload dresher:
Wenn harvester has finished his work, can AD detect  this? And Drive to harvester for unloading him?

AD define it as Final unload, and  After unload Drive to unload Destination.

**Comment by Stephan-S** [comment]
Hm,
to be honest I would have preferred it, if CP would call the unloader.
CP knows when it has finished it's work and already has the capabilities to notify about it:
vehicle.cp.driver:isWaitingForUnload()

So if this would return true after CP has finished it's work, AD would already send a driver.

Is the CP driver fired after the work is done or is he still active?
Because someone has to extend the pipe at that point and since AD isn't active on the combine I don't really want to interfere too much there if AD should detect the finished work event..

**Comment by Iwan1803** [comment]
The CP driver will not be fired automatically and CP calls an unloader only if a defined tank level has reached.

**Comment by geo-luchs** [comment]
Hi.
Thanks for detailed Info.
Athen I will request it on cp Site.

I Think it should be possible for them. Because they notice it with a blue Line that HE reached the Ende. Athen it should be possible , top,  At this point to call the unload function

**Comment by geo-luchs** [comment]
Today evening I will test the newest CPU Version. They worked already in my issue.

**Comment by Iwan1803** [comment]
I saw it and will also test it 😉

**Comment by geo-luchs** [comment]
It's working fine with cP ....320.

So, CP did his job. 
AD is unloading, and then he will wait in the field.

on CP site, they defined a new "status" 
 self.fieldWorkUnloadOrRefillState = self.states.WAITING_FOR_UNLOAD_AFTER_COURSE_ENDED

How AD is detecting , that CP is waiting for unload? Is it possible, to detect this special status, so , that AD could drive automatically to silo, and then finish his route?

**Comment by Stephan-S** [comment]
I will see what I can do about that.
Either checking the CP state or checking for crop in the area of the combine.

**Comment by Stephan-S** [comment]
Should be working right now. At least it did for two quick tests on my save :-)
Remember to use the latest CP version though!
