### ISSUE TITLE
Tipping to ground feature

### ISSUE THREAD

**Issue by fcelsa** [Stephan-S/FS19_AutoDrive#749]
Will be great if it's possible to tipping to ground goods at target destinations.

**Comment by raxtor** [comment]
I suggested it some time ago... also would be nice if "Bunker silo"mode would be able load heap from ground, not only from silo, but no idea if it is possible..

**Comment by Stephan-S** [comment]
@raxtor Isn't CP already able to do this. Loading from heaps I mean?

I implemented the buner silo mode as an extremely simplified one-click version.
But loading from heaps will likely include a lot of settings to properly define in which radius a heap should be detected, maybe even what type of heap should be targeted etc.
So I don't really like to implement this. It certainly doesn't have a high priority for me.
But since @TyKonKet seems to like your idea, he might go for it :-)

@fcelsa I personally don't like unloading heaps right into AutoDrive paths. This could cause all sorts of problems, since these paths are also always valid paths for all other drivers en route to whatever destinations.

In theory unloading to the ground is not very hard to implement but I would like to have a better concept of where to allow unloading instead of just possibly unloading at every destination

**Comment by fcelsa** [comment]
I agree with you, a viable options it's to have some special target enabled for unload on ground, this require some special settings that we need to consider space, lengths and also type of trailer.

**Comment by TyKonKet** [comment]
#129
