### ISSUE TITLE
combine problem unload 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#75]
Are people here actually get the unload combine mode to work as I have tried everything and the tractor just wont go to combine to unload

**Comment by Stephan-S** [comment]
Can you make screenshots of your settings or a video of how you setup the driver and the combine?
And are there any log errors?

**Comment by ploughedfieldman123** [comment]
Hi Stephan-S  firstly fantastic mod

Ok I have made a short video how i set up unload combine. I have also included log file 

https://youtu.be/PeVbw6rqJag

log file below 

http://www.filedropper.com/log_1

**Comment by Stephan-S** [comment]
Hey, thanks for the video and the log. There are no log errors regarding AutoDrive.
What I could not see in the video were your settings in the harvester. Did you set the same destination as the driver? So the harvester should also have "Field 21" as target. But don't activate AutoDrive there. Only select the target.
Also when you just started the game, you might have to switch into the harvester once, to actually trigger AutoDrive to be active. Giants does not update scripts on inactive vehicles. So just hire the helper and select the target in AutoDrive and it should work.
Also for small fields/distances you don't have to set the same target if in the settings menu (l-ctrt + l-alt + numpad 0) the option "find driver" is selected.

Well anyhow, I think the problem is that the AutoDrive script was not running because the combine was inactive. Can you try the steps above and share the results? Thank you for your patience :-)

**Comment by ploughedfieldman123** [comment]
Hi again Stephan-S

many thanks for your fast reply most appreciated. I have now done another short video, went to the combine. which is being used by the  FS19_AIVehicleExtension mod version 0.0.2.5.   tried 2 things but tractor still wont go to unload it 

https://www.youtube.com/watch?v=bWaNuH9fLL4&feature=youtu.be

Im a bit confused when you say  

> Also for small fields/distances you don't have to set the same target if in the settings menu (l-ctrt + l-alt + numpad 0) the option "find driver" is selected.


whats  l-ctrt + l-alt + numpad 0) the option "find driver" is selected.

**Comment by Stephan-S** [comment]
Hello again. Thanks for the video. Did you notice the small difference? The driver now said "Drive to combine". In this state he is trying to calculate a path to the pipe of the combine which avoids fruit and other collisions. Since you are on a very narrow field and had only a small fruit free section for the driver to drive on, this calculation takes a long time. After a while (depending on your framerate. Standard 2500 frames -> 2500 frames/(60 frames/s) = 41,6 seconds). If he cant't find a way in the given time, he will go into fallback mode and drive through the fruit. And if he can't even find a route in fallback mode he will switch off AutoDrive.

So, all you had to do in this case was wait about a minute longer :-) Your settings were all correct. It was simply a very hard case to find a route automatically.

If you want to help the driver, do more headland rounds, before setting the driver up.
Just play around with it and look at the status messages in the AutoDrive Hud, next to the destination name.

There is a settings menu for autoDrive and (ctrl + alt + 0) is the deafult keybinding. Just look in your keybindings settings of Farming Simulator if you want to change the keybinding.

**Comment by ploughedfieldman123** [comment]
Hi
 well after a good 3 to 4 minutes tractor did actually go to unload combine.  but now its back after unloading I must have waited a good 5 minutes for it to go to combine and it still didn't go. I must have done a good 4 headlands now.  isn't there a way to speed up him waiting to unload combine. as I could have driven it myself to combine unload it and to tip and back quicker. I think I will have to use course play for unloading combines as this is taking far too long

**Comment by Roby1164** [comment]
I think the problem is precisely in giving the Autodrive command to the combine, the combine is useless, in fact I think harmful, let it go automatically without autodrive, you will do your job. when it is full it stops and pulls out the hose, at which point the tractor, which is waiting to unload it, will leave without waiting. But in this case, I advise you to set, not to park in the field, but to make sure you get back to the starting point to wait for the next unloading, otherwise everything stops.

**Comment by ploughedfieldman123** [comment]
> I think the problem is precisely in giving the Autodrive command to the combine, the combine is useless, in fact I think harmful, let it go automatically without autodrive, you will do your job. when it is full it stops and pulls out the hose, at which point the tractor, which is waiting to unload it, will leave without waiting. But in this case, I advise you to set, not to park in the field, but to make sure you get back to the starting point to wait for the next unloading, otherwise everything stops.

ok thanks yes will give that a go
