### ISSUE TITLE
Traffic hang in same direction

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#79]
Yep, I see the traffic stop & wait for crossing from time ago now it's very cool, but it can make an issue when AD go in the same direction show as the picture below, because the AD can go faster than the traffic. Before the car traffic were pushed because the collisionTrigger was not taken into account but it wasn't go up on it ^^. I think maybe too you cannot say to the traffic wait this one but not this 2nd right or in same direction... if it is possible this should be very hard to do...
![1](https://user-images.githubusercontent.com/25174503/56449493-15f22100-631a-11e9-8cdb-f98d30e6d14c.png)
Ps: I read the requests added combine, have you made already a video demo ?
Very good job Balu AD work much much better as before !
Ano

**Comment by Stephan-S** [comment]
Hey, sorry to disappoint you Anonymous, but I will not support AI traffic due to this exact problem. AutoDrive could detect them as obstacle and stop, but what's the point if they still stop dead in the middle of the road.

I stand with my recommendation: "Switch traffic off when using AutoDrive".
Maybe this will change someday, but not anytime soon. Sorry

**Comment by Anonymous-any** [comment]
No problem I was thinking you maybe can solve this. Also added to that I can observe is sometimes when I switch vehicle with Tab and Tab-back, traffic vehicle simply disappear then AD can continue, and last night with this trick I got a game crash :p
For my memory isn't some previous versions FS19 the tractors pushed the car traffic no ? or I'm confounds with FS17...
