### ISSUE TITLE
same thing cant export routes error

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#82]
2019-04-20 15:16 C:/Users/stan/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveXML.lua:373: invalid value (nil) at index 1 in table for 'concat'

I have copied a AutoDrive_Marwell_Manor_Farm_config.xml from a backup save placed it in savegame  but in the game if I alter a route it wont now export

**Comment by Anonymous-any** [comment]
Hi maybe before alter a route, have you tried to use the export function icon like floppy disk, then import function ? (buttons need to be set for import) and must be do 2 time imported if you never tried that ! the one time is for AD create the import folder and 2nd when you put or move your fresh export file inside this folder then you import at this time with your buttons you have set, then recalculate. I think this is the best way for AD try to repair you look bad route file...
Regard

**Comment by ploughedfieldman123** [comment]
> Hi maybe before alter a route, have you tried to use the export function icon like floppy disk, then import function ? (buttons need to be set for import) and must be do 2 time imported if you never tried that ! the one time is for AD create the import folder and 2nd when you put or move your fresh export file inside this folder then you import at this time with your buttons you have set, then recalculate. I think this is the best way for AD try to repair you look bad route file...
> Regard

I cant understand what you really mean I know about that export icon what looks like floppy disc, when I recalcuate routes I always hit that export icon. I dont know what you mean by   

> buttons need to be set for import) and must be do 2 time imported 

can you do a short video

**Comment by Anonymous-any** [comment]
Not really but I try to continue where you are hang...I can add you some screenshot eventually but it's not specially need to be wizard for do it and found that. This is a bit long but I try to be much detailed explain, my english is bad if you prefer French ? ... :)
What I have understand at your 1st post is you had used a file from one of your savegameBackup folder to try to repair or/and replace your altered file at the usable savegame folder, I hope I just ?

Ok I understand you good export the recalculated file and it is registered in his `FS19_AutoDrive_Export` folder (for information it normally got a lower size compared to the AD file who is inside the savegameXX folder). The question that come to me is why you export a file you don't use then ? or maybe I've not just understand your 1st post, but it's not the goal... the followed

1) Now you need to set import button for AD that make sense because you exported the file who it logically need to be imported now don't you think ? then for do that go into menu option then scroll down for found the AD import command and set to attribute button/s for this and it's ok (for me I put Crtl+LShift+I) but you have to put your better choice and not conflicted with other thing it's logical like this:
![1](https://user-images.githubusercontent.com/25174503/56474849-0856ab80-6480-11e9-8aee-ab2050f2bd48.png)
2) After do that I was say you above you should have to do 2 times the import command I repeat, (Crtl+LShift+I for me) but it's maybe better for you you will have to create the `FS19_AutoDrive_Import` (strict name folder) yourself before and copy or move the route exported file inside (the one from the `FS19_AutoDrive_Export` folder). By this way you will have only to do one time the import command so you choose your best way you want for you, then in game after you do imported the command it show you the line where you import the file in the .log file and how many points are in the imported file.
When it's done you put recalculate, then you try to go to a destination, then you quit the full game normally without using q/quit from the console command if you usually use it's very important !
Then re-launch your game and see if it's done you should be able to continue to add your route without error ? !
I cannot say better...

**Comment by Anonymous-any** [comment]
@ploughedfieldman123 are you able to repair your route then ?

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123 are you able to repair your route then ?

Yes its all sorted now thanks.

whats this AutoDrive Course Editor folder do can we edit routes out of the game then

**Comment by Anonymous-any** [comment]
Very cool glad you've been rebuild it. It can contain lots routes so but all the merit only returns to Balu !
Yes you right `AutoDrive Course Editor` tool is for edit AD route out of game but it need JAVA engine on your computer to run AD.jar.
Regard

**Comment by ploughedfieldman123** [comment]
> Very cool glad you've been rebuild it. It can contain lots routes so but all the merit only returns to Balu !
> Yes you right `AutoDrive Course Editor` tool is for edit AD route out of game but it need JAVA engine on your computer to run AD.jar.
> Regard

I have java installed on my PC, But nothing will start the editor.  how do you run this editor

**Comment by Roby1164** [comment]
> > Very cool glad you've been rebuild it. It can contain lots routes so but all the merit only returns to Balu !
> > Yes you right `AutoDrive Course Editor` tool is for edit AD route out of game but it need JAVA engine on your computer to run AD.jar.
> > Regard
> 
> I have java installed on my PC, But nothing will start the editor. how do you run this editor

What Java do you have installed on your PC? What SO do you have on the PC?
If you are on windows 10, check here, if it is updated:
https://www.java.com/en/download/

**Comment by ploughedfieldman123** [comment]
> > > Very cool glad you've been rebuild it. It can contain lots routes so but all the merit only returns to Balu !
> > > Yes you right `AutoDrive Course Editor` tool is for edit AD route out of game but it need JAVA engine on your computer to run AD.jar.
> > > Regard
> > 
> > 
> > I have java installed on my PC, But nothing will start the editor. how do you run this editor
> 
> What Java do you have installed on your PC? What SO do you have on the PC?
> If you are on windows 10, check here, if it is updated:
> https://www.java.com/en/download/

Ok I have now installed this java from the link above. but what do I have to click on to start the editor

**Comment by Roby1164** [comment]
First on AD, to start the program.
Then on Load Config, and go get the XML file that you find in your savegame, for the map, it depends on what you use, if they are the base ones, look at them in the program folder, in SCR / mapimages, otherwise you have to get the map file what do you use:
http://prntscr.com/ng8amp
http://prntscr.com/ng8b47

**Comment by Roby1164** [comment]
> I load the config file AutoDrive_Marwell_Manor_Farm_config.xml from export folder
> 
> I load map by clicking on the .i3d file but nothing happens

No, the PNG image file is needed for the map

**Comment by ploughedfieldman123** [comment]
> > I load the config file AutoDrive_Marwell_Manor_Farm_config.xml from export folder
> > I load map by clicking on the .i3d file but nothing happens
> 
> No, the PNG image file is needed for the map

Hi thanks Roby1164  its all working ok now,  but if i click on save at top right. I then get a window which just says open or cancel  so how can you save what you have done like delete a point or what ever else 

<a href="https://ibb.co/rMv5ZLk"><img src="https://i.ibb.co/J2Crzbn/ADSAVE.jpg" alt="ADSAVE" border="0"></a>

**Comment by Roby1164** [comment]
Yes, when you save, you have to overwrite what you have in the savegame folder, in that way you save the new points, and in the game you will find the modified paths,
If you intend tractors to go in reverse, it is not possible, the tracks can be one-way or two-way, but you always need a fillet connection, so that the vehicles go back.

**Comment by ploughedfieldman123** [comment]
> Yes, when you save, you have to overwrite what you have in the savegame folder, in that way you save the new points, and in the game you will find the modified paths,
> If you intend tractors to go in reverse, it is not possible, the tracks can be one-way or two-way, but you always need a fillet connection, so that the vehicles go back.

Hi again Roby1164 thanks for getting back to me.  you say you have to overwrite whats in savegame folder but it dont have a save option  all it says is open or cancel

whats a fillet connection

also another question. each time you modify a route say in the game do you always export each time. then when starting a game copy that to import folder 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/YZs8qmD/saving.jpg" alt="saving" border="0"></a>

**Comment by Roby1164** [comment]
Open = overwrite .....

Those PNG files, they are only the map images, they don't change, the data you need are in the XML file, which overwrite them in the savegame folder, you don't need to import anything ...

**Comment by ploughedfieldman123** [comment]
> Open = overwrite .....
> 
> Those PNG files, they are only the map images, they don't change, the data you need are in the XML file, which overwrite them in the savegame folder, you don't need to import anything ...

so you just say open then look for that cfg file in savegame 

so why do i have a FS19_AutoDrive_Export and  FS19_AutoDrive_Import  folders in this path

c:\Users\PC\Documents\My Games\FarmingSimulator2019\

also where should the folder called FS19_AutoDrive-master be located to work and the images. as mine dont seem to load up now

**Comment by Roby1164** [comment]
You're getting a little confused .....
Let's start with the file you need for the tracks in the game, which is in the savegame folder, it's called this: AutoDrive_Fenton_ (your map) __ config.xml, and it's the one to overwrite when you make changes with the editor.
The FS19_AutoDrive-master folder is the one you extract when you download the mod from github, but it's the master, so there's everything in it, from the sources, to the zipped mod, and even the editor folder, and no nva put in the mod folder of the game.
The FS19_AutoDrive_Export and FS19_AutoDrive_Import folders, I believe that created them, when you used the function in play, export, but they are not necessary for the game.

Attention if you use the saving on the cloud of Steam, that when starting the game, you have to overwrite the changes made to the Savegame folder, then cancel the changes made with the editor, in theory it should say that there is a difference between the local savgame and the one on the cloud, then asks you to choose which one to use, and you have to say, the local one, updating the one on the cloud ....

**Comment by ploughedfieldman123** [comment]
> Attention if you use the saving on the cloud of Steam, that when starting the game, you have to overwrite the changes made to the Savegame folder, then cancel the changes made with the editor, in theory it should say that there is a difference between the local savgame and the one on the cloud, then asks you to choose which one to use, and you have to say, the local one, updating the one on the cloud ....

I dont understand this bit. above, as I dont use steam cloud.  all i did was to remove some waypoints. in editor, saved them. went into game and like i said the route still was ok, even though I removed some points.

when you say I have to overwrite changes to the savegame cfg file. dont the AD editor do that when you save then. after making changes to routes in editor.
