### ISSUE TITLE
nichts geht mehr

### ISSUE THREAD

**Issue by RalfGorden** [Stephan-S/FS19_AutoDrive#824]
hallo hab gerade die 1.0.6.7 hochgeladen selbst gepackt , seitdem geht garnichts mehr richtig 

er zeigt nicht mehr Grün an was er gerade macht
er läd nicht mehr ab am Trigger 
fährt dem Ernter hinten drauf 
mehrere Ziele anfahren geht auch nicht, fährt immer nur zu einen Ziel an dann muss ich kurz ausmachen dann wieder an  
er sagt auch das er den Weg nicht findet Abfahrer Feld 15  den hab ich garnicht eingestellt wie man im Foto sieht
hab ein paar Fotos gemacht
![fsScreen_2019_11_08_14_07_01](https://user-images.githubusercontent.com/56214377/68480341-de56b200-0234-11ea-8038-0b986605fb81.png)
![fsScreen_2019_11_08_14_07_27](https://user-images.githubusercontent.com/56214377/68480342-deef4880-0234-11ea-86e5-7aac7598aabc.png)
![fsScreen_2019_11_08_14_11_37](https://user-images.githubusercontent.com/56214377/68480345-deef4880-0234-11ea-8bb6-c99ca834e170.png)

**Comment by geo-luchs** [comment]
see also :
#825 
#822

**Comment by Iwan1803** [comment]
Das Fehler passieren können, ist menschlich, aber in den letzten Tagen scheinen sich die zu häufen oder kommt es mir nur so vor?

**Comment by RalfGorden** [comment]
das sollte keine Kritik sein von mir sondern nur zur Fehlerbehebung dienen , Stefan mach weiter so 👍

**Comment by Bobster82** [comment]
> Das Fehler passieren können, ist menschlich, aber in den letzten Tagen scheinen sich die zu häufen oder kommt es mir nur so vor?

If you want to improve things, you can easily destroy things. Its hard to satisfy everyone ;)

**Comment by ratze68** [comment]
Kann ich auch bestätigen.
Selbst die abfahre bei den Mähdrescher bleiben stehen oder drehen im Kreis. Sieht lustig aus....

macht weiter so!!

**Comment by haamic** [comment]
Ich spiele die letzten Tage nicht mit dem LS19, verfolge aber mit Besorgnis die sich häufenden Fehlermeldungen. 
@Stephan-S  
Es gibt ein Sprichwort, "viele Köche verderben den Brei ",  kann es sein, dass derzeit viele darin "rumrühren"? 
ich wäre dafür, erstmal den SP relativ fehlerfrei zu bekommen, bevor man auf Fehler im MP reagiert und evtl. dadurch wieder den SP "kaputt" macht.  So kommt es mir in letzter Zeit leider vor. 
Gruß Micha

**Comment by Stephan-S** [comment]
We have a new programmer in the team. And he is doing a lot of restructuring of the code right now, which I totally welcome.
It's a good chance for him to get to know the codebase and it's good for the mod itself since it receives some needed restructuring which I kind of delayed and rather focused on bug reports and new features.

Of course all this restructuring will lead to some problems which he and I will not always catch right away. So currently be aware of this process and only use the release zips if you want to have the most stable experience. (I know, not perfect but mostly stable :-) )
If you want to help us out and catch the bugs that occur during this process, feel free to use the latest sources and report issues here.

Also, I am not having a lot of time for AutoDrive as I am pretty much at work all the time and I'm away from my main machine at home during the weekdays. So please appreciate @TyKonKet for his work and I'm sure you will be happy he joined the team after he's done restructuring and helps you out with your issues and implements new features.
He has already done some work on the Multiplayer event handling and improved the user experience for the input masks for destination names and some more.

Be patient, we are only humans here and we only have so much time to spent on developing this mod for free for you guys :-)

Keep up the great community here. I really enjoy having you all participate here! :-)

**Comment by geo-luchs** [comment]
I thought this already, that he is new and has to learn how the code works.
Maybe you @Stephan-S  know, that I also had sometimes a look into the code, and I'm very impressed. So I can feel with him what does that mean to work on code, which he didn't developped.

And you are right, you can't check everything. Therefor we have the community.
For me, it'S clear, the github zip is more for special users, who wants to test and give you feedback.

Together we all will improve it.

Looking forward and I'm happy to have Autodrive

Thanks for your work

**Comment by ratze68** [comment]
Hallo Stephan,
ich kann mich nur meine Vorredner anschließen!

Habe jetzt zwei stundem mit AD gespielt, folgendes ist mir auf gefallen.

Alle auch Claas DLC abfahrer bleiben bei Produktionen und Verkaufsstellen stehen
Das abfahren von Mähdrescher funktioniert tatenlos mit Fahrzeuge von Claas DLC. Bei Standards Fahrzeug nicht. Die bleiben einfach stehen finden kein Ziel.

Macht weiter AutoDrive ist Klasse

Lg Stefan

**Comment by RalfGorden** [comment]
hallo habe jetzt nochmal ein wenig getestet die 65,66 und 67, ich muss sagen einigermaßen Spielbar ist bei mir nur die 1.0.6.5 gerade  das soll keine Kritik sein ,macht weiter so Daumen hoch

**Comment by Iwan1803** [comment]
@Stephan-S 
es ist gut, das du Unterstützung hast, aber es sollte nach Möglichkeit nicht passieren, das etwas hochgeladen und bereitgestellt wird, was zu Fehlern führt, welches ein Spielen unmöglich macht. 
Ich weiß nicht, in wie weit Github das unterstützt oder ob man außerhalb machen muss, aber kann man sowas wie eine Art Beta-Testergruppe machen? Heißt, bevor etwas veröffentlicht wird, erhält diese Gruppe die geänderten Dateien, testet diese und erst dann werden sie veröffentlicht. Vielleicht geht das auch mit einem 2. Ordner oder so, kA.

**Comment by geo-luchs** [comment]
Letztendlich macht Stephan doch wöchentlich ein Release. Dazwischen lädt sich jeder das Github source ZIP runter, um zu testen.

Es wäre leider noch mehr Aufwand, wenn er eine Gruppe pflegen müsste, falls github das technisch überhaupt unterstützt.

Und er ist nun mal aufs Feedback angewiesen.
Nochmal zur Erinnerung: er hat keine kommerzielle Softwarebude, sondern macht das aus Spaß.
Ich hoffe, dass möglichst viele hier auch die Gelegenheit nutzen, ihm mal nen Kaffee zu spendieren ( hab ich auch schon gemacht).

Also, testet alle fleißig weiter , und meldet Fehler, ich mach es auch.

Manchmal ist es halt so, dass es dann viel Zeit kostet, und man nicht richtig spielen kann.
Dafür gibt es dann wieder Zips, wo was richtig Gutes hinzugekommen ist.

Stephan, dein Mod ist TOP und sehr hilfreich

**Comment by Bobster82** [comment]
> @Stephan-S
> es ist gut, das du Unterstützung hast, aber es sollte nach Möglichkeit nicht passieren, das etwas hochgeladen und bereitgestellt wird, was zu Fehlern führt, welche ein Spielen unmöglich machen.
> Ich weiß nicht, in wie weit Github das unterstützt oder ob man das außerhalb machen muss, aber kann man sowas wie eine Art Beta-Testergruppe machen? Heißt, bevor etwas veröffentlicht wird, erhält diese Gruppe die geänderten Dateien, testet diese und erst dann werden sie veröffentlicht. Vielleicht geht das auch mit einem 2. Ordner oder so, kA.

As stephan said a lot of times, you can download the zips or u can experiment with the files in map autodrive, where little commits are uploaded. You can go for the more stable zips or go for expermental and help out finding the bugs. Pick the zip file that works best for you.... BUT its all not "perfect"..... Dont request for perfect as the coders are doing this in their spare time! A lot of testing is needed... Rather help out and report the bugs so they can fix them if possible ;)

**Comment by Iwan1803** [comment]
Warum habe ich das Gefühl, das einige hier jedes Wort auf die Goldwaage legen oder den Sinn eines Beitrages gerne mal verdrehen oder einfach die Hintergründe nicht kennen und dann sinnlos irgendwas raushauen?
Nur zur Info: ich bin Programmierer und das nicht nur im Job sondern auch in ein paar privaten Projekten. Daher weiß ich, wie das so läuft und das vor allen in privaten Projekten aus Zeitmangel oder mangelndem QS-Verständnis gerne mal etwas "geschludert" wird. Wir sind alle nur Menschen und niemand hier erwartet 100% Perfektion (was auch niemals möglich sein wird). Es werden immer Fehler passieren, aber wenn man einige davon im vorhinein ausschließen kann, indem man z.Bsp. gewisse Regeln festlegt, kann das ja eigentlich nur von Vorteil sein. 
Ich möchte hier niemandem etwas vorschreiben, sondern einfach nur helfen, die Qualität der Releases (und der Betas) zu verbessern, damit es eben nicht dazu kommt, das man einen Totalausfall erleidet und z.Bsp. nicht mal mehr seinen Spielstand laden kann. Da alle das in ihrer privaten Zeit machen, dauert ein Bugfixing nun mal eben etwas länger und das sollten alle im Hinterkopf haben (auch die Entwickler).
Und ja, ich habe bisher immer die aktuellste statt der letzten Zip-Release-Version verwendet, aber aufgrund der letzten Fehler setze ich erstmal aus. Mit den Bugs in der Version auf meinem Rechner kann ich zumindest spielen, auch wenn es zwischendurch tierisch nervt, wenn die Abfahrer auf dem Feld mal wieder den Weg zum Startpunkt nicht finden oder an einem Zielpunkt sinnlos kreiseln (ggfs. Wendekreis falsch berechnet?).
Also, alle mal wieder runterkommen und Stephan und sein Team einfach mal machen lassen...

**Comment by Bobster82** [comment]
All I say is that it is normal and completely legal to up a code that has bugs for people to test them out ;) @Iwan1803 you go in the offence of saying that upping a code with bugs is not ok... you as programmer would know how nice it is to have a group of testers ;) releasing something that can break a game is ok to me, thats just testing out a code for a programmer... if it doesnt work, just grab the release before that commit ;)
Im not trying to attack you, but give the programmers here a bit more air ;)  Maybe as you write in german and I in english, we could make mistakes too haha..
Have a nice day

**Comment by Iwan1803** [comment]
Deutsch ist nun mal meine Sprache und wenn ich meine Kommentare übersetze oder übersetzen lasse, geht teilweise der Sinn verloren.... 😋
Nochmal: es geht mir lediglich darum, um mögliche vermeidbare Bugs auch zu vermeiden.
einfaches Bsp.: "Spiel lädt nicht mehr" könnte man vermutlich verhindern, indem man seinen Code einfach mal durch einen Neustart des Spiels gegentestet, bevor man den Code hochlädt.
Das Code auf der eigenen Maschine funktioniert und auf anderen dann komischerweise nicht mehr kenne ich leider nur zu gut und sowas ist eben auch nicht vermeidbar, aber Code sollte nur dann übermittelt werden, wenn er nach bestem Wissen und Gewissen getestet worden ist (wenn man denn die Möglichkeiten dazu hat).
Hier sind nun mal als erstes die Entwickler gefragt und meine Intention ist nicht, irgendjemanden zu irgendwas zu drängen, zumal mir das auch gar nicht zu steht 😉

**Comment by Stephan-S** [comment]
To keep this international and allow my team member to also understand this I'll stay with english for now :-)

So, you both have valid point.
It's a matter of definition. Whether you see this repository itself or at least the master branch as stable or at least beta worthy or not.
I usually tried to only upload code that I had at least tested and it wasn't throwing errors in my savegame. But since the possible configurations right now are endless, not all bugs can be detected by simply starting a game and maybe starting a few AD drivers.
We have many modes now in AutoDrive, countless settings which affect which part of the code is run and which isn't even touched.
Also some errors may occur on brand new savegames with or without init config. Some are only present on dedicated servers while other show up on hosted servers.

So providing a bug free and thoroughly tested version is not really viable with the time constraints we are working with here.
Unfortunately we can not run any auto generated tests here since it all relies on the Giants Engine and it's return values.
I know CP has done some mockup functions to probably do some sandbox testing but I'm not sure that this is up-to-date.

For now, we go on with pushing commit that are at least running in our test savegames and where we tested the functionality we tried to change or the bug we wanted to fix.
I already had a conversation with @TyKonKet to make sure we are on the same page from now on! So I don't think you have to be to scared about trying new commits once we got rid of the currently bugged version.
But the release zip will still be the most stable one we could produce at that time and I totally understand if someone decides to stay with those or even revert to a version that was working for the features he uses the most.

Anyhow I've gotta stop writing these long messages and start fixing bugs :-)

**Comment by geo-luchs** [comment]
coming back to testing.
I've downloaded today 1.0.6.7-2

First test results:
- Now , when starting AD, it shows me directly the current target as green 
- He is unloading at the trigger 
- but "stopping" at unload destination and wait for "drive forward" button --> I've created an own issue for that
- I didn't got anymore the message that he can't the path to any destination I've not set for this vehicle.

**Comment by Stephan-S** [comment]
So I'll close this issue for now as it seems we caught the bugs that were introduced by the restructuring.
If I missed anything, please open a seperate issue for every bug so I can keep track of it.
Thank you guys!
