### ISSUE TITLE
unloader waiting at unload position

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#837]
AutoDrive Version: 1.0.6.7-2
Release or custom zip: custom-zip
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**
Harvester (CP) is working on the field.
Tractor is waiting on the field for unload the harvester.
--> mode "Unload combine"

He is unloading the harvester.
When trailer is full, he is driving to silo, unloading, but then he is "stopping" at unload destination, but AD active and waiting. Field destination is already green.

When pressing the "driving forward" button, he is driving back to the field.

Error: why he is waiting at unload destination for "drive forward" button ?

![driver_is_not_driving_back_to_field](https://user-images.githubusercontent.com/53658780/68535499-adb16e00-0343-11ea-92f9-534dacbbe1b9.png)

**Comment by Stephan-S** [comment]
hey @geo-luchs 
Thank you for the nice bug report.
It's fixed now.

Another question. I'm looking to expand the team here a bit. The community who uses AutoDrive seems to be growing and the reported issues are sure piling up.
I spent more time lately answering issues, reading through them, sorting them in categories etc.

We sure could use some 'official' moderators here on the Github. And since you are quite active for some time now, I would like to invite you into the team and grant you some rights to handle and moderate the issues here as you see fit.
I could also convince @Iwan1803 to accept this proposal yesterday :D

**Comment by geo-luchs** [comment]
Thanks for this offer. I will try to contact you personally via mail
And this bug report: I've to thank you, I've used only the template. It's really good now to have these buttons for creating the bugs.

**Comment by geo-luchs** [comment]
Tested with 1.0.6.7-3  : OK
