### ISSUE TITLE
Italian and Spanish translations

### ISSUE THREAD

**Issue by Stephan-S** [Stephan-S/FS19_AutoDrive#85]
Hey guys, I would like to submit an update to the modhub. Is anyone here fluent in italian or spanish and can update the translations in the moddesc.xml? I would really appreciate it :-)
Thank you!

**Comment by Roby1164** [comment]
I have seen that the Italian translation has already been completed, but I would like to indicate an error here:

<text name="gui_ad_parkInField_tooltip">
			<en>After unloading a combine - if not parked in fruit</en>
			<de>Nach Drescher abladen - falls nicht in Frucht stehend</de>
			**<it>Dopo aver scaricato la trebbia - se non parcheggiata sul raccolto</it>**
			<fr>Après avoir déchargé une moissonneuse - si pas garé en fruit</fr>	
		</text>

The most correct sentence would be:

**<it>Dopo aver scaricato la trebbia - non parcheggiare sul raccolto</it>**

The rest is ok.

**Comment by cristiancundari** [comment]
Not really, the meaning of that is: if the combine is parked in fruit then after unloading go to the waiting position; if not stay where you are on the field.
So it's correct to say:

Parcheggia sul campo:
Dopo aver scaricato la trebbia - se non parcheggiata sul raccolto

I'm going to do another pull request to adjust some other small comprehension errors.

**Comment by Roby1164** [comment]
> Not really, the meaning of that is: if the combine is parked in fruit then after unloading go to the waiting position; if not stay where you are on the field.
> So it's correct to say:
> 
> Parcheggia sul campo:
> Dopo aver scaricato la trebbia - se non parcheggiata sul raccolto
> 
> I'm going to do another pull request to adjust some other small comprehension errors.

Ti rispondo in italiano che faccio prima. La funzione è che: Cosa fare dopo aver scaricato la mietitrebbia ?
Se gli si da l'impostazione di restare dove si trova, allora potrebbe essere nella parte di campo già raccolta, oppure in quella ancora da raccogliere, in base a dove il tubo della mietitrebbia si trovava. Quindi, impostando questa opzione, si dice, cosa deve fare, di conseguenza la domanda corretta è: " Dopo aver scaricato la Trebbia - resto fermo o mi sposto fuori dal campo ? "
Questo in base a come funziono adesso quell'impostazione, che gli diamo, 1 resta fermo, se non è pronto per andare a scaricare, mentre se gli diamo 2, si sposta al punto di partenza.

Excuse me Stephan for the Italian, but otherwise I couldn't explain myself well, I try to get you a translation.
I answer you in Italian that I do first. The function is that: What to do after downloading the combine?
If you give it the setting to stay where it is, then it could be in the already harvested part of the field, or in that still to be collected, depending on where the combine's hose was. So, setting this option, it says, what it has to do, therefore the correct question is:
" Dopo aver scaricato la Trebbia - resto fermo o mi sposto fuori dal campo ? "
This based on how I work now that setting, which we give it, 1 remains still, if it is not ready to go to download, while if we give it 2, it moves to the starting point.

**Comment by cristiancundari** [comment]
I've just created a pull request to fix this.

**Comment by PromGames** [comment]
#90

**Comment by Roby1164** [comment]
Here in the game (Italian): The setting asks you to tell what to do after downloading the mititrebbia, so the correct description, both in English and translated into various languages, is:
After downloading the combine, do I stop on the field and go back to the starting point?
The setting, in fact, changes the way we behave, if we give it YES, it stays where it is, whether it is on the crop or on the already harvested field, while if we give it NO, then it returns to the starting point.
In Italian, the right description, so it will be:
" Dopo aver scaricato la trebbia, resto sul campo o vado al punto di partenza ? "
![Screenshot_5](https://user-images.githubusercontent.com/24955554/56521642-f4757d00-6545-11e9-8965-db9067564db4.jpg)

**Comment by Pitufo306** [comment]
> Hola chicos, me gustaría enviar una actualización al modhub. ¿Alguien aquí es fluido en italiano o español y puede actualizar las traducciones en el moddesc.xml? Realmente lo 
> agradecería :-) ¡ Gracias!

I could help out with Spanish.

**Comment by Stephan-S** [comment]
Thanks for your help.
I will close this issue for now and reopen a new one if new translations are desperately required.
Many thanks to all contributors!
