### ISSUE TITLE
new releases

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#86]
when you download the zip called FS19_AutoDrive-master.zip  I always replace  FS19_AutoDrive.zip  in the mods folder with latest version from the releases folder.  but in the   FS19_AutoDrive-master.zip is a folder called FS19_AutoDrive and if you check the modDesc.xml in that folder its same as one in releases folder. but some of the files are different sizes to whats in releases folder.  so which 1 is to use. as  I always use 1 from releases folder 

also where is the change log so we know whats been updated

**Comment by Stephan-S** [comment]
They are called 'releases' for a reason :-)
Just use the zip files in the release folder. You can also directly download the current zip file.
So for example if you want the current version 1.0.1.5, then just navigate to it in the browser:
https://github.com/Stephan-S/FS19_AutoDrive/blob/master/releases/1.0.1.5/FS19_AutoDrive.zip
and then click the "Download" button.
No need to download the complete repository all the time :-)

But anyhow, the filesizes should usually match because I create the most current release version from these files in the folder. If they are different in size, you might be looking at them in the zip file, where the file sizes obviously change.
