### ISSUE TITLE
Unloading combine - pathfinding issue

### ISSUE THREAD

**Issue by rgoe** [Stephan-S/FS19_AutoDrive#860]
Hi there,
I've an issue with pathfinding in mode combine unloading - unloader finds no path.

AutoDrive Version: 1.0.6.8 and 1.0.6.7
Release (both)
Map: MultiMap 2019
Vehicle / type (applicable): Combine: NH CR10.90 (Vanilla), Claas Arion 660 (DLC), NH T6 (Vanilla). Case IH Maxxum (Vanilla)  - all three with TKD 302 Trailer (Vanilla)

**Describe the bug**
CP driving combine on Multimap 2019 field 10, fill level reached, calling unloader.
All three unloaders showing same behavior: Starting to calculate route and giving up - "can't calculate a path" - no difference if fruit avoidance is on or off.

**If applicable - Steps to reproduce the behavior**
Setup combine for field 10 on MultiMap 2019 and assign an unloader with AD.
![fsScreen_2019_11_12_00_03_17](https://user-images.githubusercontent.com/21224499/68628854-1a626f00-04e2-11ea-8f61-1147207b3ac6.png)
![fsScreen_2019_11_12_00_03_35](https://user-images.githubusercontent.com/21224499/68628864-20585000-04e2-11ea-8095-529d98877bc8.png)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3833570/log.txt)

**Screenshots**
Two screenshots attached showing positions and setup, two videos with AD 1.0.6.7 and 1.0.6.8.
AD 1.0.6.7: https://www.youtube.com/watch?v=mgSpk5FG9bA&t=4s
AD 1.0.6.8: https://www.youtube.com/watch?v=rfWcNBu0diY

Best regards and thx for the hard work on this mod.

**Comment by geo-luchs** [comment]
We have this Problem reported already several times.   
Sometimes it' s Not finding the path, or it's driving die Circles.

**Comment by raxtor** [comment]
You can set time for path calculation... I think max is 3x longer than default... sometimes can help change target in combine when u was manipulating with network..

**Comment by rgoe** [comment]
I have already tried to increase the time for calculating the route, unfortunately to no avail.

What I additionally noticed (same map&field), when the combine has reached the "up and down" part of the course shown above - after doing 2 headlands:
- when the pipe of the combine is on the fruit-side (combine heading south towards the waiting unloaders) so that the unloader has to do a 180 degree turn during their approach to reach the combine from behind the problem persists.
- when the pipe is not on the fruit (combine heading north) and the unloader can approach the combine in a more or less straight line - it works most of the time.
As mentioned above - turning off/on fruit avoidance makes no difference.

**Comment by Stephan-S** [comment]
You have enabled the debug mode in AutoDrive.
This will allow you too see the pathfinder in action.
In the 1.0.6.8 version is currently an error that causes the driver to try to start at the current angle of the combine. This is almost the reverse direction of the tractor and heads right for the tree and the truck itself. So this doesn't work.

In 1.0.6.7 it works but since you have the debug mode enabled, you can even see it. As soon as the pathfinder is done, you can see the resulting path if you look around and also the exact Nodes he will follow. You can see that in your video. If you want the tractor to continue, you have to disable the edit mode.
This is just for debugging purposes if the pathfinder isn't working and should not be used in normal operation!

But for the 1.0.6.8 version, the debug view was helpful! Although this is already fixed in the sources :-)

**Comment by rgoe** [comment]
Yes - I turned debug on just for the video/error reporting to give you as much information as possible.
I'm already testing with the latest github-version and it looks really good - and thanks for the clarification regarding edit/debug mode. I think this issue is solved therefore I'm closing this it.
Thanks for the quick support and reply!!

**Comment by raxtor** [comment]
@Stephan-S just  a question.. isnt possible show calculated path always when u turn on debug function.. can be useful when there is any trouble (circle stuck, combine crash, obstacle crash).. now its only displayed when calculation is done and vehicle is starting move.. or? More useful will be version if problem is active but in that case calculated path is already invisible...
