### ISSUE TITLE
Rubicon 9000 is not ablle follow course

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#886]
AutoDrive Version: 1.0.6.8-10
Map (if applicable): All
Vehicle / type (applicable): Rubicon 9000

Vehicle is not able follow course
![fsScreen_2019_11_17_02_38_05](https://user-images.githubusercontent.com/831266/69001709-c1c91280-08e3-11ea-8297-da66560d4d31.png)

**Comment by Iwan1803** [comment]
Maybe some more informations would be good...

**Comment by Stephan-S** [comment]
No, it's alright. I'm on it.
For some reason, with the Rubicon, the player steering isn't disabled.
So AD/AI steering is offline. It only controls velocity but not the steering. The player can still control that.

This is a new issue and I have to check if this is related to something AD did with all the restructuring or if it caused by a recent FS update

**Comment by raxtor** [comment]
Its caused by AD, earlier versions worked ok.. it similar bug to New Holland front loader if u remeber @Stephan-S
