### ISSUE TITLE
Error: [AutoDrive] Encountered a problem during initialization - shutting down

### ISSUE THREAD

**Issue by MacedonskyAlex** [Stephan-S/FS19_AutoDrive#896]
If the tractor is very close to the exit point, then the tractor cannot calculate the route. I put the maximum detour at 1000 meters - this does not help.

video >>> https://www.youtube.com/watch?v=uNhAHa4w3fI&t=39s

**Comment by MacedonskyAlex** [comment]
The tractor cannot determine the combine unloading trigger, but this only happens at the end point when the combine has completed its work. I also often notice that tractors often come across a combine

video >>> https://www.youtube.com/watch?v=aq2h4Dt72S4

**Comment by Woife1** [comment]
the setting what you meant is for extra meters in a tour to be faster or avoid destinations (the translation from Stephan is right i think ;) )
your 2. point works in my setting 
they only wants to drive over the cutter ;)

**Comment by KCHARRO** [comment]
In another issue I mentioned that this happens when the combine goes back to unload and is at the edge of the field, the assistant does not calculate because he tries to create a path within the boundaries of the field, and being the combine outside it cannot approach.

I solved this using CoursePlay by creating a course with three or four laps around the field, and so there is room for the combine not to be out of the field even if it goes back with the pocket maneuver (I always do this because I play maps that do not have the fields squares),

In square fields it also does it if the combi is left out or on the limit. (I solved it in the same way)

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
