### ISSUE TITLE
Non-functional code in method `AutoDrive:startAD`?

### ISSUE THREAD

**Issue by DeckerMMIV** [Stephan-S/FS19_AutoDrive#922]
May I question what the purpose is, in the `AutoDrive:startAD` method, to call the `AutoDrive:FastShortestPath` method with a non-defined variable `closest` (i.e. a nil value)?

Wouldn't that result in an empty table, that is assigned to `vehicle.ad.wayPoints`?

Perhaps this hasn't been discovered yet, due to the later call to `AutoDrive:initializeAD`, which "fixes" it, by making a correct call to `AutoDrive:FastShortestPath`?

**Comment by TyKonKet** [comment]
@DeckerMMIV I think you are right 😄

**Comment by Stephan-S** [comment]
That probably slipped by me when I made some refactoring regarding the 'closest' variable which is now cached for one frame since it is possibly used in many locations/loops.
Thanks for pointing this out :-)
The only code that is needed there is the 'skipStart' flag which decides which destination to aim for first (Target or unload point). The rest is done in the initialize step.
