### ISSUE TITLE
Pathfinding not limited to field

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#929]
AutoDrive Version: 1.0.6.9-14 custom zip
Map (if applicable): All

when unloading the combine, the pathfinding of truck / tractor is not limited to the field anymore. 

Seems to happen especially when the combine turned lanes, the unloader wants to turn outside the field.

**Comment by Stephan-S** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/3-AutoDrive-modes:#353-restrict-to-field

If he stands close to the field border he has no choice but to ignore the settings if he can't find a path on the field

**Comment by SledgeHammer75** [comment]
https://filebin.net/ftiem4b6xaf3hzr5/Farming_Simulator_19_2019-11-23_18-32-02-1.m4v?t=uiob4779

is this a case of to close to the border?

**Comment by Stephan-S** [comment]
yeah, the problem is the position of the combine. The pathfinder is trying to follow the combine, which means he is aiming a certain distance behind the combine which is not reacheable while staying on the field. So I either have to make him wait for a better situation or you have to do more headlands, correct :-)
