### ISSUE TITLE
AD doesn't load the sowing machine

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#965]
Ad 1.7.0.10 beladet die Sähmaschine nicht  ich Spiele auf der Suedhemmern mir einem Plazirbaren Saatgut und Düngersilo und Ad befüllt die Sähmaschiene nicht.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3905207/log.txt)

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
